const fs = require("fs");
const path = require("path");

const compiledIndexPath = path.resolve(__dirname, "..", ".tmp", "validation", "src", "data", "index.js");
const compiledFingerprintPath = path.resolve(__dirname, "..", ".tmp", "validation", "src", "data", "content-fingerprint.js");
const outputPath = path.resolve(__dirname, "..", "src", "data", "content-approvals.ts");

if (!fs.existsSync(compiledIndexPath) || !fs.existsSync(compiledFingerprintPath)) {
  throw new Error("Compiled validation artifacts not found. Run `npm run prepare:content` first.");
}

const { DISEASE_STATES } = require(compiledIndexPath);
const { buildContentApprovalFingerprintMap } = require(compiledFingerprintPath);

const approvals = buildContentApprovalFingerprintMap(DISEASE_STATES);
const file = `// AUTO-GENERATED by scripts/approve-content.js
// Run \`npm run approve:content\` only after clinically reviewing changed disease content.

export const APPROVED_CONTENT_VERSIONS: Record<string, string> = ${JSON.stringify(approvals, null, 2)};
`;

fs.writeFileSync(outputPath, file);
console.log(`Wrote ${path.relative(process.cwd(), outputPath)}`);
