import type { DiseaseCatalogSummary, MonographCatalogSummary } from "../types";

// AUTO-GENERATED by scripts/generate-catalog-manifest.js
// Run `npm run generate:catalog-manifest` after changing disease content.

export const DISEASE_CATALOG: DiseaseCatalogSummary[] = [
  {
    "id": "uti",
    "name": "Urinary Tract Infections",
    "icon": "🔬",
    "category": "Infectious Disease",
    "subcategoryCount": 4,
    "monographCount": 6,
    "contentMeta": {
      "confidence": "high",
      "lastReviewed": "2026-03-09",
      "guidelineVersion": "IDSA 2025 cUTI guidance",
      "sources": [
        {
          "id": "idsa-2025-cuti",
          "citation": "Infectious Diseases Society of America complicated UTI guidance, 2025."
        },
        {
          "id": "idsa-escmid-2011-uti",
          "citation": "International Clinical Practice Guidelines for uncomplicated cystitis and pyelonephritis, 2011."
        },
        {
          "id": "eau-2024-uti",
          "citation": "European Association of Urology UTI guidance, 2024."
        }
      ],
      "reviewHistory": [
        {
          "reviewedOn": "2026-03-09",
          "reviewedBy": "PharmRef editorial review",
          "summary": "Reviewed 2025 cUTI reclassification, shorter-course recommendations, and IV-to-PO bacteremic UTI guidance."
        }
      ],
      "reviewedBy": "PharmRef editorial review",
      "reviewScope": "Disease overview review",
      "governance": {
        "owner": "PharmRef editorial review",
        "approvedBodyVersion": "0686bd80"
      }
    }
  },
  {
    "id": "cap",
    "name": "Community-Acquired Pneumonia",
    "icon": "🫁",
    "category": "Infectious Disease",
    "subcategoryCount": 5,
    "monographCount": 5,
    "contentMeta": {
      "confidence": "high",
      "lastReviewed": "2026-03-09",
      "guidelineVersion": "ATS/IDSA 2019 CAP guidance",
      "sources": [
        {
          "id": "ats-idsa-2019-cap",
          "citation": "Adult community-acquired pneumonia guideline from ATS and IDSA, 2019."
        },
        {
          "id": "cape-cod",
          "citation": "Hydrocortisone for severe CAP, NEJM 2023."
        },
        {
          "id": "el-moussaoui-2006-short-course-cap",
          "citation": "Three-day versus eight-day amoxicillin strategy after early clinical stability in adult CAP, BMJ 2006."
        }
      ],
      "reviewHistory": [
        {
          "reviewedOn": "2026-03-09",
          "reviewedBy": "PharmRef editorial review",
          "summary": "Reviewed outpatient and inpatient CAP regimen selection, STEP short-course data, and severe CAP steroid updates."
        }
      ],
      "reviewedBy": "PharmRef editorial review",
      "reviewScope": "Disease overview review",
      "governance": {
        "owner": "PharmRef editorial review",
        "approvedBodyVersion": "a0e2b5b4"
      }
    }
  },
  {
    "id": "hap-vap",
    "name": "Hospital-Acquired & Ventilator-Associated Pneumonia",
    "icon": "🏥",
    "category": "Infectious Disease",
    "subcategoryCount": 4,
    "monographCount": 5,
    "contentMeta": {
      "confidence": "moderate",
      "lastReviewed": "2026-03-09",
      "guidelineVersion": "ATS/IDSA 2016 HAP/VAP guidance",
      "sources": [
        {
          "id": "ats-idsa-2016-hap-vap",
          "citation": "Hospital-acquired and ventilator-associated pneumonia guideline, 2016."
        },
        {
          "id": "idsa-2024-amr",
          "citation": "Antimicrobial resistance guidance used for resistant gram-negative escalation decisions, 2024."
        },
        {
          "id": "smart-trial",
          "citation": "Balanced crystalloids versus saline in ICU patients, NEJM 2018."
        }
      ],
      "reviewHistory": [
        {
          "reviewedOn": "2026-03-09",
          "reviewedBy": "PharmRef editorial review",
          "summary": "Reviewed HAP/VAP empiric coverage, resistant gram-negative escalation, and ICU stewardship framing."
        }
      ],
      "reviewedBy": "PharmRef editorial review",
      "reviewScope": "Disease overview review",
      "governance": {
        "owner": "PharmRef editorial review",
        "approvedBodyVersion": "afce7228"
      }
    }
  },
  {
    "id": "ssti",
    "name": "Skin & Soft Tissue Infections",
    "icon": "🩹",
    "category": "Infectious Disease",
    "subcategoryCount": 4,
    "monographCount": 3,
    "contentMeta": {
      "confidence": "moderate",
      "lastReviewed": "2026-03-09",
      "guidelineVersion": "IDSA SSTI guidance",
      "sources": [
        {
          "id": "idsa-2014-ssti",
          "citation": "Skin and soft tissue infection guidance from IDSA."
        },
        {
          "id": "idsa-2024-amr",
          "citation": "Resistant organism escalation guidance, 2024."
        },
        {
          "id": "oviva",
          "citation": "Oral versus intravenous antibiotics for bone and joint and deep infection pathways, NEJM 2019."
        }
      ],
      "reviewHistory": [
        {
          "reviewedOn": "2026-03-09",
          "reviewedBy": "PharmRef editorial review",
          "summary": "Reviewed purulent and nonpurulent SSTI pathways, MRSA coverage boundaries, and oral step-down strategy."
        }
      ],
      "reviewedBy": "PharmRef editorial review",
      "reviewScope": "Disease overview review",
      "governance": {
        "owner": "PharmRef editorial review",
        "approvedBodyVersion": "1f543a5e"
      }
    }
  },
  {
    "id": "iai",
    "name": "Intra-Abdominal Infections",
    "icon": "🫁",
    "category": "Infectious Disease",
    "subcategoryCount": 4,
    "monographCount": 3,
    "contentMeta": {
      "confidence": "moderate",
      "lastReviewed": "2026-03-09",
      "guidelineVersion": "SIS/IDSA intra-abdominal infection guidance",
      "sources": [
        {
          "id": "idsa-sis-2010-ciai",
          "citation": "IDSA/SIS 2010 guideline for diagnosis and management of complicated intra-abdominal infection."
        },
        {
          "id": "sis-2017-ciai",
          "citation": "Surgical Infection Society 2017 revised guidance for intra-abdominal infection."
        },
        {
          "id": "tokyo-guidelines",
          "citation": "Biliary and cholecystitis/cholangitis guidance used for source-control framing."
        },
        {
          "id": "stop-it",
          "citation": "Short-course antimicrobial therapy for source-controlled intra-abdominal infection, NEJM 2015."
        }
      ],
      "reviewHistory": [
        {
          "reviewedOn": "2026-03-09",
          "reviewedBy": "PharmRef editorial review",
          "summary": "Reviewed source-control-first IAI management, biliary coverage boundaries, and short-course post-control durations."
        }
      ],
      "reviewedBy": "PharmRef editorial review",
      "reviewScope": "Disease overview review",
      "governance": {
        "owner": "PharmRef editorial review",
        "approvedBodyVersion": "7473d77a"
      }
    }
  },
  {
    "id": "amr-gn",
    "name": "AMR Gram-Negative Infections",
    "icon": "🛡️",
    "category": "Antimicrobial Resistance — IDSA 2024 Guidance (Tamma et al.)",
    "subcategoryCount": 6,
    "monographCount": 3,
    "contentMeta": {
      "confidence": "high",
      "lastReviewed": "2026-03-09",
      "guidelineVersion": "IDSA 2024 AMR guidance",
      "sources": [
        {
          "id": "idsa-2024-amr",
          "citation": "Guidance for ESBL-E, CRE, DTR Pseudomonas, and resistant Acinetobacter, 2024."
        },
        {
          "id": "merino",
          "citation": "Piperacillin-tazobactam versus meropenem for ESBL bacteremia, JAMA 2018."
        },
        {
          "id": "pkpd-stewardship",
          "citation": "Extended-infusion beta-lactam stewardship principles used throughout resistant gram-negative pathways."
        }
      ],
      "reviewHistory": [
        {
          "reviewedOn": "2026-03-09",
          "reviewedBy": "PharmRef editorial review",
          "summary": "Reviewed IDSA AMR mechanism-based therapy, carbapenem-sparing strategy, and extended-infusion beta-lactam use."
        }
      ],
      "reviewedBy": "PharmRef editorial review",
      "reviewScope": "Disease overview review",
      "governance": {
        "owner": "PharmRef editorial review",
        "approvedBodyVersion": "839cd9b5"
      }
    }
  },
  {
    "id": "bacteremia-endocarditis",
    "name": "Bacteremia & Endocarditis",
    "icon": "🩸",
    "category": "Infectious Disease — AHA/ESC Guidance",
    "subcategoryCount": 5,
    "monographCount": 5,
    "contentMeta": {
      "confidence": "high",
      "lastReviewed": "2026-03-09",
      "guidelineVersion": "ESC 2023 + AHA 2015 IE guidance",
      "sources": [
        {
          "id": "esc-2023-ie",
          "citation": "Current European infective endocarditis guideline update, 2023."
        },
        {
          "id": "aha-2015-ie",
          "citation": "Foundational AHA scientific statement for adult infective endocarditis, 2015."
        },
        {
          "id": "poet",
          "citation": "Partial oral treatment of endocarditis, NEJM 2019."
        },
        {
          "id": "arrest",
          "citation": "Adjunctive rifampin for Staphylococcus aureus bacteremia, Lancet 2018."
        }
      ],
      "reviewHistory": [
        {
          "reviewedOn": "2026-03-09",
          "reviewedBy": "PharmRef editorial review",
          "summary": "Reviewed bloodstream infection duration, endocarditis evaluation, and oral or OPAT transition criteria."
        }
      ],
      "reviewedBy": "PharmRef editorial review",
      "reviewScope": "Disease overview review",
      "governance": {
        "owner": "PharmRef editorial review",
        "approvedBodyVersion": "b8fce25d"
      }
    }
  },
  {
    "id": "c-difficile",
    "name": "Clostridioides difficile Infection",
    "icon": "🦠",
    "category": "Infectious Disease — IDSA/SHEA 2021 + ACG 2021",
    "subcategoryCount": 6,
    "monographCount": 4,
    "contentMeta": {
      "confidence": "high",
      "lastReviewed": "2026-03-09",
      "guidelineVersion": "IDSA/SHEA CDI guidance",
      "sources": [
        {
          "id": "idsa-shea-cdi",
          "citation": "Clostridioides difficile infection guideline from IDSA and SHEA."
        },
        {
          "id": "fidaxomicin-trials",
          "citation": "Registration and recurrence-reduction trials informing fidaxomicin preference."
        },
        {
          "id": "fmt-stewardship",
          "citation": "Evidence base for fecal microbiota transplant in multiply recurrent CDI."
        }
      ],
      "reviewHistory": [
        {
          "reviewedOn": "2026-03-09",
          "reviewedBy": "PharmRef editorial review",
          "summary": "Reviewed CDI severity stratification, fidaxomicin preference, and recurrence-prevention escalation."
        }
      ],
      "reviewedBy": "PharmRef editorial review",
      "reviewScope": "Disease overview review",
      "governance": {
        "owner": "PharmRef editorial review",
        "approvedBodyVersion": "f1cb706e"
      }
    }
  },
  {
    "id": "bone-joint",
    "name": "Bone & Joint Infections",
    "icon": "🦴",
    "category": "Infectious Disease — IDSA 2015 + OVIVA 2019",
    "subcategoryCount": 4,
    "monographCount": 2,
    "contentMeta": {
      "confidence": "moderate",
      "lastReviewed": "2026-03-09",
      "guidelineVersion": "OVIVA-informed bone and joint guidance",
      "sources": [
        {
          "id": "oviva",
          "citation": "Oral versus intravenous antibiotics for bone and joint infection, NEJM 2019."
        },
        {
          "id": "idsa-2013-pji",
          "citation": "IDSA prosthetic joint infection guideline used for surgical strategy and hardware retention decisions."
        },
        {
          "id": "orthopedic-id-review",
          "citation": "Orthopedic infection source-control and step-down stewardship literature."
        }
      ],
      "reviewHistory": [
        {
          "reviewedOn": "2026-03-09",
          "reviewedBy": "PharmRef editorial review",
          "summary": "Reviewed osteomyelitis and prosthetic-joint step-down strategy, source control, and OVIVA-aligned oral therapy."
        }
      ],
      "reviewedBy": "PharmRef editorial review",
      "reviewScope": "Disease overview review",
      "governance": {
        "owner": "PharmRef editorial review",
        "approvedBodyVersion": "f975f540"
      }
    }
  },
  {
    "id": "cns-infections",
    "name": "CNS Infections",
    "icon": "🧠",
    "category": "Infectious Disease — IDSA 2004/2017 + ESCMID 2016",
    "subcategoryCount": 3,
    "monographCount": 2,
    "contentMeta": {
      "confidence": "moderate",
      "lastReviewed": "2026-03-09",
      "guidelineVersion": "IDSA CNS infection guidance",
      "sources": [
        {
          "id": "idsa-2004-bacterial-meningitis",
          "citation": "IDSA bacterial meningitis guideline for community-acquired disease."
        },
        {
          "id": "idsa-2017-ventriculitis-meningitis",
          "citation": "IDSA healthcare-associated ventriculitis and meningitis guideline."
        },
        {
          "id": "idsa-2008-encephalitis",
          "citation": "IDSA encephalitis guideline used for diagnostic framing and early empiric antiviral therapy."
        },
        {
          "id": "dexamethasone-meningitis",
          "citation": "Adjunctive dexamethasone trials informing pneumococcal meningitis care."
        }
      ],
      "reviewHistory": [
        {
          "reviewedOn": "2026-03-09",
          "reviewedBy": "PharmRef editorial review",
          "summary": "Reviewed meningitis and ventriculitis empiric therapy, adjunctive dexamethasone use, and CNS diagnostic priorities."
        }
      ],
      "reviewedBy": "PharmRef editorial review",
      "reviewScope": "Disease overview review",
      "governance": {
        "owner": "PharmRef editorial review",
        "approvedBodyVersion": "15d02b75"
      }
    }
  },
  {
    "id": "fungal-infections",
    "name": "Fungal Infections",
    "icon": "🍄",
    "category": "IDSA 2016 Candidiasis & Aspergillosis Guidelines · Antifungal Stewardship",
    "subcategoryCount": 4,
    "monographCount": 4,
    "contentMeta": {
      "confidence": "moderate",
      "lastReviewed": "2026-03-09",
      "guidelineVersion": "IDSA 2016 candidiasis and aspergillosis guidance",
      "sources": [
        {
          "id": "idsa-candidiasis",
          "citation": "Clinical practice guideline for candidiasis, IDSA 2016."
        },
        {
          "id": "idsa-aspergillosis",
          "citation": "Diagnosis and management of aspergillosis, IDSA 2016."
        },
        {
          "id": "secure-trial",
          "citation": "Isavuconazole versus voriconazole for invasive aspergillosis, Lancet 2016."
        }
      ],
      "reviewHistory": [
        {
          "reviewedOn": "2026-03-09",
          "reviewedBy": "PharmRef editorial review",
          "summary": "Reviewed candidiasis and aspergillosis first-line agents, salvage roles, and therapeutic monitoring priorities."
        }
      ],
      "reviewedBy": "PharmRef editorial review",
      "reviewScope": "Disease overview review",
      "governance": {
        "owner": "PharmRef editorial review",
        "approvedBodyVersion": "d114a7a8"
      }
    }
  },
  {
    "id": "advanced-agents",
    "name": "Advanced & Resistant Pathogen Agents",
    "icon": "🛡",
    "category": "Infectious Disease",
    "subcategoryCount": 2,
    "monographCount": 8,
    "contentMeta": {
      "confidence": "emerging",
      "lastReviewed": "2026-03-09",
      "guidelineVersion": "IDSA 2022-2024 resistant pathogen guidance",
      "sources": [
        {
          "id": "idsa-2024-amr",
          "citation": "Guidance for CRE, ESBL-E, DTR Pseudomonas, and resistant gram-negatives."
        },
        {
          "id": "aspect-cuti-ciai",
          "citation": "Ceftolozane-tazobactam cUTI and cIAI registration data."
        },
        {
          "id": "aspect-np",
          "citation": "Ceftolozane-tazobactam nosocomial pneumonia phase 3 data."
        },
        {
          "id": "restore-imi",
          "citation": "Imipenem-cilastatin-relebactam versus polymyxin-based therapy."
        }
      ],
      "reviewHistory": [
        {
          "reviewedOn": "2026-03-09",
          "reviewedBy": "PharmRef editorial review",
          "summary": "Reviewed reserve-agent positioning for resistant gram-negatives and stewardship boundaries for novel therapies."
        }
      ],
      "reviewedBy": "PharmRef editorial review",
      "reviewScope": "Disease overview review",
      "governance": {
        "owner": "PharmRef editorial review",
        "approvedBodyVersion": "75ed9261"
      }
    }
  },
  {
    "id": "febrile-neutropenia",
    "name": "Febrile Neutropenia",
    "icon": "🩻",
    "category": "Infectious Disease",
    "subcategoryCount": 3,
    "monographCount": 0,
    "contentMeta": {
      "confidence": "moderate",
      "lastReviewed": "2026-03-09",
      "guidelineVersion": "IDSA febrile neutropenia guidance",
      "sources": [
        {
          "id": "idsa-febrile-neutropenia",
          "citation": "Guideline for evaluation and management of febrile neutropenia in cancer patients."
        },
        {
          "id": "nccn-fever-neutropenia",
          "citation": "NCCN references for risk stratification and outpatient eligibility."
        },
        {
          "id": "mascc-risk-index",
          "citation": "MASCC risk index used for outpatient eligibility and early disposition."
        },
        {
          "id": "cisne-score",
          "citation": "CISNE score used to refine low-risk classification in clinically stable solid-tumor outpatients."
        }
      ],
      "reviewHistory": [
        {
          "reviewedOn": "2026-03-09",
          "reviewedBy": "PharmRef editorial review",
          "summary": "Reviewed high-risk febrile neutropenia initial coverage, escalation triggers, and outpatient risk stratification."
        }
      ],
      "reviewedBy": "PharmRef editorial review",
      "reviewScope": "Disease overview review",
      "governance": {
        "owner": "PharmRef editorial review",
        "approvedBodyVersion": "a5889938"
      }
    }
  },
  {
    "id": "diabetic-foot",
    "name": "Diabetic Foot Infections",
    "icon": "🦶",
    "category": "Infectious Disease",
    "subcategoryCount": 4,
    "monographCount": 0,
    "contentMeta": {
      "confidence": "moderate",
      "lastReviewed": "2026-03-09",
      "guidelineVersion": "IWGDF/IDSA diabetic foot guidance",
      "sources": [
        {
          "id": "iwgdf-idsa-dfi",
          "citation": "Diabetic foot infection guidance from IWGDF and IDSA."
        },
        {
          "id": "lazaro-martinez-2014-dfi-osteomyelitis",
          "citation": "Probe-to-bone and imaging-supported management strategy for suspected diabetic foot osteomyelitis."
        },
        {
          "id": "iwgdf-2023-wound-classification",
          "citation": "Wound classification and perfusion framing used to guide source control, limb threat staging, and debridement urgency."
        }
      ],
      "reviewHistory": [
        {
          "reviewedOn": "2026-03-09",
          "reviewedBy": "PharmRef editorial review",
          "summary": "Reviewed diabetic foot severity staging, debridement and perfusion priorities, and osteomyelitis step-down options."
        }
      ],
      "reviewedBy": "PharmRef editorial review",
      "reviewScope": "Disease overview review",
      "governance": {
        "owner": "PharmRef editorial review",
        "approvedBodyVersion": "be6561f9"
      }
    }
  },
  {
    "id": "sepsis",
    "name": "Sepsis & Septic Shock",
    "icon": "🔴",
    "category": "Critical Care / Infectious Disease",
    "subcategoryCount": 3,
    "monographCount": 0,
    "contentMeta": {
      "confidence": "high",
      "lastReviewed": "2026-03-09",
      "guidelineVersion": "SSC 2021 + Sepsis-3 + BALANCE 2024",
      "sources": [
        {
          "id": "ssc-2021",
          "citation": "Surviving Sepsis Campaign international guidelines, 2021."
        },
        {
          "id": "sepsis-3",
          "citation": "Consensus definitions and diagnostic framework for sepsis and septic shock, JAMA 2016."
        },
        {
          "id": "balance",
          "citation": "Seven versus fourteen days for bloodstream infection, 2024."
        }
      ],
      "reviewHistory": [
        {
          "reviewedOn": "2026-03-09",
          "reviewedBy": "PharmRef editorial review",
          "summary": "Reviewed early sepsis antimicrobials, resistant-risk stratification, and shorter-course de-escalation evidence."
        }
      ],
      "reviewedBy": "PharmRef editorial review",
      "reviewScope": "Disease overview review",
      "governance": {
        "owner": "PharmRef editorial review",
        "approvedBodyVersion": "301ffb35"
      }
    }
  }
];

export const MONOGRAPH_CATALOG: MonographCatalogSummary[] = [
  {
    "id": "nitrofurantoin",
    "name": "Nitrofurantoin",
    "drugClass": "Nitrofuran antibiotic",
    "parentDiseaseId": "uti",
    "parentDiseaseName": "Urinary Tract Infections"
  },
  {
    "id": "tmp-smx",
    "name": "Trimethoprim-Sulfamethoxazole",
    "drugClass": "Folate pathway inhibitor (dihydrofolate reductase inhibitor + dihydropteroate synthase inhibitor)",
    "parentDiseaseId": "uti",
    "parentDiseaseName": "Urinary Tract Infections"
  },
  {
    "id": "fosfomycin",
    "name": "Fosfomycin",
    "drugClass": "Phosphonic acid derivative (cell wall synthesis inhibitor — unique MOA)",
    "parentDiseaseId": "uti",
    "parentDiseaseName": "Urinary Tract Infections"
  },
  {
    "id": "ciprofloxacin",
    "name": "Ciprofloxacin",
    "drugClass": "Fluoroquinolone (2nd generation) — DNA gyrase and topoisomerase IV inhibitor",
    "parentDiseaseId": "uti",
    "parentDiseaseName": "Urinary Tract Infections"
  },
  {
    "id": "ceftriaxone",
    "name": "Ceftriaxone",
    "drugClass": "Third-generation cephalosporin",
    "parentDiseaseId": "uti",
    "parentDiseaseName": "Urinary Tract Infections"
  },
  {
    "id": "levofloxacin",
    "name": "Levofloxacin",
    "drugClass": "Fluoroquinolone (3rd generation, 'respiratory fluoroquinolone')",
    "parentDiseaseId": "uti",
    "parentDiseaseName": "Urinary Tract Infections"
  },
  {
    "id": "amoxicillin",
    "name": "Amoxicillin",
    "drugClass": "Aminopenicillin (beta-lactam)",
    "parentDiseaseId": "cap",
    "parentDiseaseName": "Community-Acquired Pneumonia"
  },
  {
    "id": "azithromycin",
    "name": "Azithromycin",
    "drugClass": "Macrolide (azalide subclass — 15-membered ring)",
    "parentDiseaseId": "cap",
    "parentDiseaseName": "Community-Acquired Pneumonia"
  },
  {
    "id": "doxycycline",
    "name": "Doxycycline",
    "drugClass": "Tetracycline (2nd generation — lipophilic tetracycline)",
    "parentDiseaseId": "cap",
    "parentDiseaseName": "Community-Acquired Pneumonia"
  },
  {
    "id": "moxifloxacin",
    "name": "Moxifloxacin",
    "drugClass": "Fluoroquinolone (4th generation — 'respiratory fluoroquinolone')",
    "parentDiseaseId": "cap",
    "parentDiseaseName": "Community-Acquired Pneumonia"
  },
  {
    "id": "ampicillin-sulbactam",
    "name": "Ampicillin-Sulbactam",
    "drugClass": "Aminopenicillin + beta-lactamase inhibitor (BLI)",
    "parentDiseaseId": "cap",
    "parentDiseaseName": "Community-Acquired Pneumonia"
  },
  {
    "id": "pip-tazo",
    "name": "Piperacillin-Tazobactam",
    "drugClass": "Extended-spectrum penicillin + beta-lactamase inhibitor (BLI)",
    "parentDiseaseId": "hap-vap",
    "parentDiseaseName": "Hospital-Acquired & Ventilator-Associated Pneumonia"
  },
  {
    "id": "cefepime",
    "name": "Cefepime",
    "drugClass": "Fourth-generation cephalosporin",
    "parentDiseaseId": "hap-vap",
    "parentDiseaseName": "Hospital-Acquired & Ventilator-Associated Pneumonia"
  },
  {
    "id": "vancomycin",
    "name": "Vancomycin",
    "drugClass": "Glycopeptide antibiotic",
    "parentDiseaseId": "hap-vap",
    "parentDiseaseName": "Hospital-Acquired & Ventilator-Associated Pneumonia"
  },
  {
    "id": "linezolid",
    "name": "Linezolid",
    "drugClass": "Oxazolidinone (first-in-class)",
    "parentDiseaseId": "hap-vap",
    "parentDiseaseName": "Hospital-Acquired & Ventilator-Associated Pneumonia"
  },
  {
    "id": "meropenem",
    "name": "Meropenem",
    "drugClass": "Carbapenem (beta-lactam)",
    "parentDiseaseId": "hap-vap",
    "parentDiseaseName": "Hospital-Acquired & Ventilator-Associated Pneumonia"
  },
  {
    "id": "cefazolin",
    "name": "Cefazolin",
    "drugClass": "First-generation cephalosporin",
    "parentDiseaseId": "ssti",
    "parentDiseaseName": "Skin & Soft Tissue Infections"
  },
  {
    "id": "clindamycin",
    "name": "Clindamycin",
    "drugClass": "Lincosamide antibiotic",
    "parentDiseaseId": "ssti",
    "parentDiseaseName": "Skin & Soft Tissue Infections"
  },
  {
    "id": "daptomycin",
    "name": "Daptomycin",
    "drugClass": "Cyclic lipopeptide (first-in-class)",
    "parentDiseaseId": "ssti",
    "parentDiseaseName": "Skin & Soft Tissue Infections"
  },
  {
    "id": "metronidazole",
    "name": "Metronidazole",
    "drugClass": "Nitroimidazole antibiotic",
    "parentDiseaseId": "iai",
    "parentDiseaseName": "Intra-Abdominal Infections"
  },
  {
    "id": "ampicillin-sulbactam-iai",
    "name": "Ampicillin-Sulbactam",
    "drugClass": "Aminopenicillin + beta-lactamase inhibitor",
    "parentDiseaseId": "iai",
    "parentDiseaseName": "Intra-Abdominal Infections"
  },
  {
    "id": "ertapenem",
    "name": "Ertapenem",
    "drugClass": "Group 1 Carbapenem (narrow-spectrum carbapenem)",
    "parentDiseaseId": "iai",
    "parentDiseaseName": "Intra-Abdominal Infections"
  },
  {
    "id": "ceftazidime-avibactam",
    "name": "Ceftazidime-Avibactam",
    "drugClass": "Cephalosporin + diazabicyclooctane β-lactamase inhibitor",
    "parentDiseaseId": "amr-gn",
    "parentDiseaseName": "AMR Gram-Negative Infections"
  },
  {
    "id": "meropenem-vaborbactam",
    "name": "Meropenem-Vaborbactam",
    "drugClass": "Carbapenem + cyclic boronic acid β-lactamase inhibitor",
    "parentDiseaseId": "amr-gn",
    "parentDiseaseName": "AMR Gram-Negative Infections"
  },
  {
    "id": "cefiderocol",
    "name": "Cefiderocol",
    "drugClass": "Siderophore cephalosporin (first-in-class)",
    "parentDiseaseId": "amr-gn",
    "parentDiseaseName": "AMR Gram-Negative Infections"
  },
  {
    "id": "nafcillin",
    "name": "Nafcillin",
    "drugClass": "Anti-staphylococcal penicillin (penicillinase-resistant)",
    "parentDiseaseId": "bacteremia-endocarditis",
    "parentDiseaseName": "Bacteremia & Endocarditis"
  },
  {
    "id": "fidaxomicin",
    "name": "Fidaxomicin",
    "drugClass": "Macrocyclic antibiotic (narrow-spectrum, non-systemic)",
    "parentDiseaseId": "c-difficile",
    "parentDiseaseName": "Clostridioides difficile Infection"
  },
  {
    "id": "vancomycin-oral",
    "name": "Vancomycin (Oral)",
    "drugClass": "Glycopeptide antibiotic — ORAL FORMULATION for CDI only",
    "parentDiseaseId": "c-difficile",
    "parentDiseaseName": "Clostridioides difficile Infection"
  },
  {
    "id": "bezlotoxumab",
    "name": "Bezlotoxumab",
    "drugClass": "Human monoclonal antibody (anti-toxin B)",
    "parentDiseaseId": "c-difficile",
    "parentDiseaseName": "Clostridioides difficile Infection"
  },
  {
    "id": "rifampin",
    "name": "Rifampin",
    "drugClass": "Rifamycin antibiotic (RNA polymerase inhibitor)",
    "parentDiseaseId": "bone-joint",
    "parentDiseaseName": "Bone & Joint Infections"
  },
  {
    "id": "ampicillin",
    "name": "Ampicillin",
    "drugClass": "Aminopenicillin",
    "parentDiseaseId": "cns-infections",
    "parentDiseaseName": "CNS Infections"
  },
  {
    "id": "fluconazole",
    "name": "Fluconazole",
    "drugClass": "Triazole antifungal",
    "parentDiseaseId": "fungal-infections",
    "parentDiseaseName": "Fungal Infections"
  },
  {
    "id": "micafungin",
    "name": "Micafungin",
    "drugClass": "Echinocandin antifungal (lipopeptide)",
    "parentDiseaseId": "fungal-infections",
    "parentDiseaseName": "Fungal Infections"
  },
  {
    "id": "voriconazole",
    "name": "Voriconazole",
    "drugClass": "Triazole antifungal (second-generation)",
    "parentDiseaseId": "fungal-infections",
    "parentDiseaseName": "Fungal Infections"
  },
  {
    "id": "amphotericin-b",
    "name": "Amphotericin B (Liposomal)",
    "drugClass": "Polyene antifungal (lipid formulation)",
    "parentDiseaseId": "fungal-infections",
    "parentDiseaseName": "Fungal Infections"
  },
  {
    "id": "gentamicin",
    "name": "Gentamicin",
    "drugClass": "Aminoglycoside",
    "parentDiseaseId": "advanced-agents",
    "parentDiseaseName": "Advanced & Resistant Pathogen Agents"
  },
  {
    "id": "aztreonam",
    "name": "Aztreonam",
    "drugClass": "Monobactam (beta-lactam antibiotic)",
    "parentDiseaseId": "advanced-agents",
    "parentDiseaseName": "Advanced & Resistant Pathogen Agents"
  },
  {
    "id": "ceftolozane-tazobactam",
    "name": "Ceftolozane-Tazobactam",
    "drugClass": "5th-generation cephalosporin / beta-lactamase inhibitor combination",
    "parentDiseaseId": "advanced-agents",
    "parentDiseaseName": "Advanced & Resistant Pathogen Agents"
  },
  {
    "id": "imipenem-cilastatin-relebactam",
    "name": "Imipenem-Cilastatin-Relebactam",
    "drugClass": "Carbapenem / beta-lactamase inhibitor combination",
    "parentDiseaseId": "advanced-agents",
    "parentDiseaseName": "Advanced & Resistant Pathogen Agents"
  },
  {
    "id": "colistin",
    "name": "Colistin (Polymyxin E)",
    "drugClass": "Polymyxin antibiotic",
    "parentDiseaseId": "advanced-agents",
    "parentDiseaseName": "Advanced & Resistant Pathogen Agents"
  },
  {
    "id": "tedizolid",
    "name": "Tedizolid",
    "drugClass": "Oxazolidinone antibiotic (2nd generation)",
    "parentDiseaseId": "advanced-agents",
    "parentDiseaseName": "Advanced & Resistant Pathogen Agents"
  },
  {
    "id": "posaconazole",
    "name": "Posaconazole",
    "drugClass": "Triazole antifungal",
    "parentDiseaseId": "advanced-agents",
    "parentDiseaseName": "Advanced & Resistant Pathogen Agents"
  },
  {
    "id": "liposomal-amphotericin-b",
    "name": "Liposomal Amphotericin B (L-AmB)",
    "drugClass": "Polyene antifungal — liposomal formulation",
    "parentDiseaseId": "advanced-agents",
    "parentDiseaseName": "Advanced & Resistant Pathogen Agents"
  }
];

export const DISEASE_SUMMARY_BY_ID: Record<string, DiseaseCatalogSummary> = Object.fromEntries(
  DISEASE_CATALOG.map((disease) => [disease.id, disease]),
);

export const MONOGRAPH_SUMMARY_BY_ID: Record<string, MonographCatalogSummary> = Object.fromEntries(
  MONOGRAPH_CATALOG.map((monograph) => [monograph.id, monograph]),
);
