import type { DiseaseCatalogSummary, MonographCatalogSummary } from "../types";

// AUTO-GENERATED by scripts/generate-catalog-manifest.js
// Run `npm run generate:catalog-manifest` after changing disease content.

export const DISEASE_CATALOG: DiseaseCatalogSummary[] = [
  {
    "id": "uti",
    "name": "Urinary Tract Infections",
    "icon": "🔬",
    "category": "Infectious Disease",
    "subcategoryCount": 4,
    "monographCount": 6,
    "contentMeta": {
      "confidence": "high",
      "lastReviewed": "2026-03-09",
      "guidelineVersion": "IDSA 2025 cUTI guidance",
      "sources": [
        {
          "id": "idsa-2025-cuti",
          "citation": "Infectious Diseases Society of America complicated UTI guidance, 2025."
        },
        {
          "id": "idsa-escmid-2011-uti",
          "citation": "International Clinical Practice Guidelines for uncomplicated cystitis and pyelonephritis, 2011."
        },
        {
          "id": "eau-2024-uti",
          "citation": "European Association of Urology UTI guidance, 2024."
        }
      ],
      "reviewedBy": "PharmRef editorial review",
      "reviewScope": "Disease overview review"
    }
  },
  {
    "id": "cap",
    "name": "Community-Acquired Pneumonia",
    "icon": "🫁",
    "category": "Infectious Disease",
    "subcategoryCount": 5,
    "monographCount": 5,
    "contentMeta": {
      "confidence": "high",
      "lastReviewed": "2026-03-09",
      "guidelineVersion": "ATS/IDSA 2019 CAP guidance",
      "sources": [
        {
          "id": "ats-idsa-2019-cap",
          "citation": "Adult community-acquired pneumonia guideline from ATS and IDSA, 2019."
        },
        {
          "id": "cape-cod",
          "citation": "Hydrocortisone for severe CAP, NEJM 2023."
        },
        {
          "id": "step-trial",
          "citation": "Three-day versus eight-day amoxicillin strategy for stabilized CAP, NEJM 2023."
        }
      ],
      "reviewedBy": "PharmRef editorial review",
      "reviewScope": "Disease overview review"
    }
  },
  {
    "id": "hap-vap",
    "name": "Hospital-Acquired & Ventilator-Associated Pneumonia",
    "icon": "🏥",
    "category": "Infectious Disease",
    "subcategoryCount": 4,
    "monographCount": 5,
    "contentMeta": {
      "confidence": "moderate",
      "lastReviewed": "2026-03-09",
      "guidelineVersion": "ATS/IDSA 2016 HAP/VAP guidance",
      "sources": [
        {
          "id": "ats-idsa-2016-hap-vap",
          "citation": "Hospital-acquired and ventilator-associated pneumonia guideline, 2016."
        },
        {
          "id": "idsa-2024-amr",
          "citation": "Antimicrobial resistance guidance used for resistant gram-negative escalation decisions, 2024."
        },
        {
          "id": "smart-trial",
          "citation": "Balanced crystalloids versus saline in ICU patients, NEJM 2018."
        }
      ],
      "reviewedBy": "PharmRef editorial review",
      "reviewScope": "Disease overview review"
    }
  },
  {
    "id": "ssti",
    "name": "Skin & Soft Tissue Infections",
    "icon": "🩹",
    "category": "Infectious Disease",
    "subcategoryCount": 4,
    "monographCount": 3,
    "contentMeta": {
      "confidence": "moderate",
      "lastReviewed": "2026-03-09",
      "guidelineVersion": "IDSA SSTI guidance",
      "sources": [
        {
          "id": "idsa-2014-ssti",
          "citation": "Skin and soft tissue infection guidance from IDSA."
        },
        {
          "id": "idsa-2024-amr",
          "citation": "Resistant organism escalation guidance, 2024."
        },
        {
          "id": "oviva",
          "citation": "Oral versus intravenous antibiotics for bone and joint and deep infection pathways, NEJM 2019."
        }
      ],
      "reviewedBy": "PharmRef editorial review",
      "reviewScope": "Disease overview review"
    }
  },
  {
    "id": "iai",
    "name": "Intra-Abdominal Infections",
    "icon": "🫁",
    "category": "Infectious Disease",
    "subcategoryCount": 4,
    "monographCount": 3,
    "contentMeta": {
      "confidence": "moderate",
      "lastReviewed": "2026-03-09",
      "guidelineVersion": "SIS/IDSA intra-abdominal infection guidance",
      "sources": [
        {
          "id": "sis-idsa-iai",
          "citation": "Surgical Infection Society and IDSA intra-abdominal infection guidance."
        },
        {
          "id": "tokyo-guidelines",
          "citation": "Biliary and cholecystitis/cholangitis guidance used for source-control framing."
        },
        {
          "id": "stop-it",
          "citation": "Short-course antimicrobial therapy for source-controlled intra-abdominal infection, NEJM 2015."
        }
      ],
      "reviewedBy": "PharmRef editorial review",
      "reviewScope": "Disease overview review"
    }
  },
  {
    "id": "amr-gn",
    "name": "AMR Gram-Negative Infections",
    "icon": "🛡️",
    "category": "Antimicrobial Resistance — IDSA 2024 Guidance (Tamma et al.)",
    "subcategoryCount": 6,
    "monographCount": 3,
    "contentMeta": {
      "confidence": "high",
      "lastReviewed": "2026-03-09",
      "guidelineVersion": "IDSA 2024 AMR guidance",
      "sources": [
        {
          "id": "idsa-2024-amr",
          "citation": "Guidance for ESBL-E, CRE, DTR Pseudomonas, and resistant Acinetobacter, 2024."
        },
        {
          "id": "merino",
          "citation": "Piperacillin-tazobactam versus meropenem for ESBL bacteremia, JAMA 2018."
        },
        {
          "id": "pkpd-stewardship",
          "citation": "Extended-infusion beta-lactam stewardship principles used throughout resistant gram-negative pathways."
        }
      ],
      "reviewedBy": "PharmRef editorial review",
      "reviewScope": "Disease overview review"
    }
  },
  {
    "id": "bacteremia-endocarditis",
    "name": "Bacteremia & Endocarditis",
    "icon": "🩸",
    "category": "Infectious Disease — AHA/IDSA Guidelines",
    "subcategoryCount": 5,
    "monographCount": 5,
    "contentMeta": {
      "confidence": "high",
      "lastReviewed": "2026-03-09",
      "guidelineVersion": "AHA/ACC 2023 IE update",
      "sources": [
        {
          "id": "aha-acc-2023-ie",
          "citation": "Infective endocarditis update from AHA/ACC, 2023."
        },
        {
          "id": "poet",
          "citation": "Partial oral treatment of endocarditis, NEJM 2019."
        },
        {
          "id": "arrest",
          "citation": "Adjunctive rifampin for Staphylococcus aureus bacteremia, Lancet 2018."
        }
      ],
      "reviewedBy": "PharmRef editorial review",
      "reviewScope": "Disease overview review"
    }
  },
  {
    "id": "c-difficile",
    "name": "Clostridioides difficile Infection",
    "icon": "🦠",
    "category": "Infectious Disease — IDSA/SHEA 2021 + ACG 2021",
    "subcategoryCount": 6,
    "monographCount": 4,
    "contentMeta": {
      "confidence": "high",
      "lastReviewed": "2026-03-09",
      "guidelineVersion": "IDSA/SHEA CDI guidance",
      "sources": [
        {
          "id": "idsa-shea-cdi",
          "citation": "Clostridioides difficile infection guideline from IDSA and SHEA."
        },
        {
          "id": "fidaxomicin-trials",
          "citation": "Registration and recurrence-reduction trials informing fidaxomicin preference."
        },
        {
          "id": "fmt-stewardship",
          "citation": "Evidence base for fecal microbiota transplant in multiply recurrent CDI."
        }
      ],
      "reviewedBy": "PharmRef editorial review",
      "reviewScope": "Disease overview review"
    }
  },
  {
    "id": "bone-joint",
    "name": "Bone & Joint Infections",
    "icon": "🦴",
    "category": "Infectious Disease — IDSA 2015 + OVIVA 2019",
    "subcategoryCount": 4,
    "monographCount": 2,
    "contentMeta": {
      "confidence": "moderate",
      "lastReviewed": "2026-03-09",
      "guidelineVersion": "OVIVA-informed bone and joint guidance",
      "sources": [
        {
          "id": "oviva",
          "citation": "Oral versus intravenous antibiotics for bone and joint infection, NEJM 2019."
        },
        {
          "id": "idsa-pji-osteomyelitis",
          "citation": "IDSA guidance relevant to osteomyelitis and prosthetic joint infection pathways."
        },
        {
          "id": "orthopedic-id-review",
          "citation": "Orthopedic infection source-control and step-down stewardship literature."
        }
      ],
      "reviewedBy": "PharmRef editorial review",
      "reviewScope": "Disease overview review"
    }
  },
  {
    "id": "cns-infections",
    "name": "CNS Infections",
    "icon": "🧠",
    "category": "Infectious Disease — IDSA 2004/2017 + ESCMID 2016",
    "subcategoryCount": 3,
    "monographCount": 2,
    "contentMeta": {
      "confidence": "moderate",
      "lastReviewed": "2026-03-09",
      "guidelineVersion": "IDSA CNS infection guidance",
      "sources": [
        {
          "id": "idsa-meningitis-ventriculitis",
          "citation": "IDSA guidance for bacterial meningitis and healthcare-associated ventriculitis."
        },
        {
          "id": "aan-idsa-encephalitis",
          "citation": "Consensus references used for CNS diagnostic framing and adjunctive therapy."
        },
        {
          "id": "dexamethasone-meningitis",
          "citation": "Adjunctive dexamethasone trials informing pneumococcal meningitis care."
        }
      ],
      "reviewedBy": "PharmRef editorial review",
      "reviewScope": "Disease overview review"
    }
  },
  {
    "id": "fungal-infections",
    "name": "Fungal Infections",
    "icon": "🍄",
    "category": "IDSA 2016 Candidiasis & Aspergillosis Guidelines · Antifungal Stewardship",
    "subcategoryCount": 4,
    "monographCount": 4,
    "contentMeta": {
      "confidence": "moderate",
      "lastReviewed": "2026-03-09",
      "guidelineVersion": "IDSA 2016 candidiasis and aspergillosis guidance",
      "sources": [
        {
          "id": "idsa-candidiasis",
          "citation": "Clinical practice guideline for candidiasis, IDSA 2016."
        },
        {
          "id": "idsa-aspergillosis",
          "citation": "Diagnosis and management of aspergillosis, IDSA 2016."
        },
        {
          "id": "secure-trial",
          "citation": "Isavuconazole versus voriconazole for invasive aspergillosis, Lancet 2016."
        }
      ],
      "reviewedBy": "PharmRef editorial review",
      "reviewScope": "Disease overview review"
    }
  },
  {
    "id": "advanced-agents",
    "name": "Advanced & Resistant Pathogen Agents",
    "icon": "🛡",
    "category": "Infectious Disease",
    "subcategoryCount": 2,
    "monographCount": 8,
    "contentMeta": {
      "confidence": "emerging",
      "lastReviewed": "2026-03-09",
      "guidelineVersion": "IDSA 2022-2024 resistant pathogen guidance",
      "sources": [
        {
          "id": "idsa-2024-amr",
          "citation": "Guidance for CRE, ESBL-E, DTR Pseudomonas, and resistant gram-negatives."
        },
        {
          "id": "aspect-program",
          "citation": "Ceftolozane-tazobactam registration studies for cUTI and nosocomial pneumonia."
        },
        {
          "id": "restore-imi",
          "citation": "Imipenem-cilastatin-relebactam versus polymyxin-based therapy."
        }
      ],
      "reviewedBy": "PharmRef editorial review",
      "reviewScope": "Disease overview review"
    }
  },
  {
    "id": "febrile-neutropenia",
    "name": "Febrile Neutropenia",
    "icon": "🩻",
    "category": "Infectious Disease",
    "subcategoryCount": 3,
    "monographCount": 0,
    "contentMeta": {
      "confidence": "moderate",
      "lastReviewed": "2026-03-09",
      "guidelineVersion": "IDSA febrile neutropenia guidance",
      "sources": [
        {
          "id": "idsa-febrile-neutropenia",
          "citation": "Guideline for evaluation and management of febrile neutropenia in cancer patients."
        },
        {
          "id": "nccn-fever-neutropenia",
          "citation": "NCCN references for risk stratification and outpatient eligibility."
        },
        {
          "id": "mascc-cisne",
          "citation": "Risk-stratification tools used for low-risk outpatient decision support."
        }
      ],
      "reviewedBy": "PharmRef editorial review",
      "reviewScope": "Disease overview review"
    }
  },
  {
    "id": "diabetic-foot",
    "name": "Diabetic Foot Infections",
    "icon": "🦶",
    "category": "Infectious Disease",
    "subcategoryCount": 4,
    "monographCount": 0,
    "contentMeta": {
      "confidence": "moderate",
      "lastReviewed": "2026-03-09",
      "guidelineVersion": "IWGDF/IDSA diabetic foot guidance",
      "sources": [
        {
          "id": "iwgdf-idsa-dfi",
          "citation": "Diabetic foot infection guidance from IWGDF and IDSA."
        },
        {
          "id": "osteomyelitis-stewardship",
          "citation": "Shorter-course and oral step-down literature for diabetic foot osteomyelitis."
        },
        {
          "id": "source-control-principles",
          "citation": "Surgical debridement and perfusion assessment references used in DFI pathways."
        }
      ],
      "reviewedBy": "PharmRef editorial review",
      "reviewScope": "Disease overview review"
    }
  },
  {
    "id": "sepsis",
    "name": "Sepsis & Septic Shock",
    "icon": "🔴",
    "category": "Critical Care / Infectious Disease",
    "subcategoryCount": 3,
    "monographCount": 0,
    "contentMeta": {
      "confidence": "high",
      "lastReviewed": "2026-03-09",
      "guidelineVersion": "SSC 2021; IDSA 2024 sepsis antimicrobial guidance",
      "sources": [
        {
          "id": "ssc-2021",
          "citation": "Surviving Sepsis Campaign international guidelines, 2021."
        },
        {
          "id": "idsa-2024-sepsis",
          "citation": "Infectious disease-focused antimicrobial guidance for sepsis, 2024."
        },
        {
          "id": "balance",
          "citation": "Seven versus fourteen days for bloodstream infection, 2024."
        }
      ],
      "reviewedBy": "PharmRef editorial review",
      "reviewScope": "Disease overview review"
    }
  }
];

export const MONOGRAPH_CATALOG: MonographCatalogSummary[] = [
  {
    "id": "nitrofurantoin",
    "name": "Nitrofurantoin",
    "drugClass": "Nitrofuran antibiotic",
    "parentDiseaseId": "uti",
    "parentDiseaseName": "Urinary Tract Infections"
  },
  {
    "id": "tmp-smx",
    "name": "Trimethoprim-Sulfamethoxazole",
    "drugClass": "Folate pathway inhibitor (dihydrofolate reductase inhibitor + dihydropteroate synthase inhibitor)",
    "parentDiseaseId": "uti",
    "parentDiseaseName": "Urinary Tract Infections"
  },
  {
    "id": "fosfomycin",
    "name": "Fosfomycin",
    "drugClass": "Phosphonic acid derivative (cell wall synthesis inhibitor — unique MOA)",
    "parentDiseaseId": "uti",
    "parentDiseaseName": "Urinary Tract Infections"
  },
  {
    "id": "ciprofloxacin",
    "name": "Ciprofloxacin",
    "drugClass": "Fluoroquinolone (2nd generation) — DNA gyrase and topoisomerase IV inhibitor",
    "parentDiseaseId": "uti",
    "parentDiseaseName": "Urinary Tract Infections"
  },
  {
    "id": "ceftriaxone",
    "name": "Ceftriaxone",
    "drugClass": "Third-generation cephalosporin",
    "parentDiseaseId": "uti",
    "parentDiseaseName": "Urinary Tract Infections"
  },
  {
    "id": "levofloxacin",
    "name": "Levofloxacin",
    "drugClass": "Fluoroquinolone (3rd generation, 'respiratory fluoroquinolone')",
    "parentDiseaseId": "uti",
    "parentDiseaseName": "Urinary Tract Infections"
  },
  {
    "id": "amoxicillin",
    "name": "Amoxicillin",
    "drugClass": "Aminopenicillin (beta-lactam)",
    "parentDiseaseId": "cap",
    "parentDiseaseName": "Community-Acquired Pneumonia"
  },
  {
    "id": "azithromycin",
    "name": "Azithromycin",
    "drugClass": "Macrolide (azalide subclass — 15-membered ring)",
    "parentDiseaseId": "cap",
    "parentDiseaseName": "Community-Acquired Pneumonia"
  },
  {
    "id": "doxycycline",
    "name": "Doxycycline",
    "drugClass": "Tetracycline (2nd generation — lipophilic tetracycline)",
    "parentDiseaseId": "cap",
    "parentDiseaseName": "Community-Acquired Pneumonia"
  },
  {
    "id": "moxifloxacin",
    "name": "Moxifloxacin",
    "drugClass": "Fluoroquinolone (4th generation — 'respiratory fluoroquinolone')",
    "parentDiseaseId": "cap",
    "parentDiseaseName": "Community-Acquired Pneumonia"
  },
  {
    "id": "ampicillin-sulbactam",
    "name": "Ampicillin-Sulbactam",
    "drugClass": "Aminopenicillin + beta-lactamase inhibitor (BLI)",
    "parentDiseaseId": "cap",
    "parentDiseaseName": "Community-Acquired Pneumonia"
  },
  {
    "id": "pip-tazo",
    "name": "Piperacillin-Tazobactam",
    "drugClass": "Extended-spectrum penicillin + beta-lactamase inhibitor (BLI)",
    "parentDiseaseId": "hap-vap",
    "parentDiseaseName": "Hospital-Acquired & Ventilator-Associated Pneumonia"
  },
  {
    "id": "cefepime",
    "name": "Cefepime",
    "drugClass": "Fourth-generation cephalosporin",
    "parentDiseaseId": "hap-vap",
    "parentDiseaseName": "Hospital-Acquired & Ventilator-Associated Pneumonia"
  },
  {
    "id": "vancomycin",
    "name": "Vancomycin",
    "drugClass": "Glycopeptide antibiotic",
    "parentDiseaseId": "hap-vap",
    "parentDiseaseName": "Hospital-Acquired & Ventilator-Associated Pneumonia"
  },
  {
    "id": "linezolid",
    "name": "Linezolid",
    "drugClass": "Oxazolidinone (first-in-class)",
    "parentDiseaseId": "hap-vap",
    "parentDiseaseName": "Hospital-Acquired & Ventilator-Associated Pneumonia"
  },
  {
    "id": "meropenem",
    "name": "Meropenem",
    "drugClass": "Carbapenem (beta-lactam)",
    "parentDiseaseId": "hap-vap",
    "parentDiseaseName": "Hospital-Acquired & Ventilator-Associated Pneumonia"
  },
  {
    "id": "cefazolin",
    "name": "Cefazolin",
    "drugClass": "First-generation cephalosporin",
    "parentDiseaseId": "ssti",
    "parentDiseaseName": "Skin & Soft Tissue Infections"
  },
  {
    "id": "clindamycin",
    "name": "Clindamycin",
    "drugClass": "Lincosamide antibiotic",
    "parentDiseaseId": "ssti",
    "parentDiseaseName": "Skin & Soft Tissue Infections"
  },
  {
    "id": "daptomycin",
    "name": "Daptomycin",
    "drugClass": "Cyclic lipopeptide (first-in-class)",
    "parentDiseaseId": "ssti",
    "parentDiseaseName": "Skin & Soft Tissue Infections"
  },
  {
    "id": "metronidazole",
    "name": "Metronidazole",
    "drugClass": "Nitroimidazole antibiotic",
    "parentDiseaseId": "iai",
    "parentDiseaseName": "Intra-Abdominal Infections"
  },
  {
    "id": "ampicillin-sulbactam-iai",
    "name": "Ampicillin-Sulbactam",
    "drugClass": "Aminopenicillin + beta-lactamase inhibitor",
    "parentDiseaseId": "iai",
    "parentDiseaseName": "Intra-Abdominal Infections"
  },
  {
    "id": "ertapenem",
    "name": "Ertapenem",
    "drugClass": "Group 1 Carbapenem (narrow-spectrum carbapenem)",
    "parentDiseaseId": "iai",
    "parentDiseaseName": "Intra-Abdominal Infections"
  },
  {
    "id": "ceftazidime-avibactam",
    "name": "Ceftazidime-Avibactam",
    "drugClass": "Cephalosporin + diazabicyclooctane β-lactamase inhibitor",
    "parentDiseaseId": "amr-gn",
    "parentDiseaseName": "AMR Gram-Negative Infections"
  },
  {
    "id": "meropenem-vaborbactam",
    "name": "Meropenem-Vaborbactam",
    "drugClass": "Carbapenem + cyclic boronic acid β-lactamase inhibitor",
    "parentDiseaseId": "amr-gn",
    "parentDiseaseName": "AMR Gram-Negative Infections"
  },
  {
    "id": "cefiderocol",
    "name": "Cefiderocol",
    "drugClass": "Siderophore cephalosporin (first-in-class)",
    "parentDiseaseId": "amr-gn",
    "parentDiseaseName": "AMR Gram-Negative Infections"
  },
  {
    "id": "nafcillin",
    "name": "Nafcillin",
    "drugClass": "Anti-staphylococcal penicillin (penicillinase-resistant)",
    "parentDiseaseId": "bacteremia-endocarditis",
    "parentDiseaseName": "Bacteremia & Endocarditis"
  },
  {
    "id": "fidaxomicin",
    "name": "Fidaxomicin",
    "drugClass": "Macrocyclic antibiotic (narrow-spectrum, non-systemic)",
    "parentDiseaseId": "c-difficile",
    "parentDiseaseName": "Clostridioides difficile Infection"
  },
  {
    "id": "vancomycin-oral",
    "name": "Vancomycin (Oral)",
    "drugClass": "Glycopeptide antibiotic — ORAL FORMULATION for CDI only",
    "parentDiseaseId": "c-difficile",
    "parentDiseaseName": "Clostridioides difficile Infection"
  },
  {
    "id": "bezlotoxumab",
    "name": "Bezlotoxumab",
    "drugClass": "Human monoclonal antibody (anti-toxin B)",
    "parentDiseaseId": "c-difficile",
    "parentDiseaseName": "Clostridioides difficile Infection"
  },
  {
    "id": "rifampin",
    "name": "Rifampin",
    "drugClass": "Rifamycin antibiotic (RNA polymerase inhibitor)",
    "parentDiseaseId": "bone-joint",
    "parentDiseaseName": "Bone & Joint Infections"
  },
  {
    "id": "ampicillin",
    "name": "Ampicillin",
    "drugClass": "Aminopenicillin",
    "parentDiseaseId": "cns-infections",
    "parentDiseaseName": "CNS Infections"
  },
  {
    "id": "fluconazole",
    "name": "Fluconazole",
    "drugClass": "Triazole antifungal",
    "parentDiseaseId": "fungal-infections",
    "parentDiseaseName": "Fungal Infections"
  },
  {
    "id": "micafungin",
    "name": "Micafungin",
    "drugClass": "Echinocandin antifungal (lipopeptide)",
    "parentDiseaseId": "fungal-infections",
    "parentDiseaseName": "Fungal Infections"
  },
  {
    "id": "voriconazole",
    "name": "Voriconazole",
    "drugClass": "Triazole antifungal (second-generation)",
    "parentDiseaseId": "fungal-infections",
    "parentDiseaseName": "Fungal Infections"
  },
  {
    "id": "amphotericin-b",
    "name": "Amphotericin B (Liposomal)",
    "drugClass": "Polyene antifungal (lipid formulation)",
    "parentDiseaseId": "fungal-infections",
    "parentDiseaseName": "Fungal Infections"
  },
  {
    "id": "gentamicin",
    "name": "Gentamicin",
    "drugClass": "Aminoglycoside",
    "parentDiseaseId": "advanced-agents",
    "parentDiseaseName": "Advanced & Resistant Pathogen Agents"
  },
  {
    "id": "aztreonam",
    "name": "Aztreonam",
    "drugClass": "Monobactam (beta-lactam antibiotic)",
    "parentDiseaseId": "advanced-agents",
    "parentDiseaseName": "Advanced & Resistant Pathogen Agents"
  },
  {
    "id": "ceftolozane-tazobactam",
    "name": "Ceftolozane-Tazobactam",
    "drugClass": "5th-generation cephalosporin / beta-lactamase inhibitor combination",
    "parentDiseaseId": "advanced-agents",
    "parentDiseaseName": "Advanced & Resistant Pathogen Agents"
  },
  {
    "id": "imipenem-cilastatin-relebactam",
    "name": "Imipenem-Cilastatin-Relebactam",
    "drugClass": "Carbapenem / beta-lactamase inhibitor combination",
    "parentDiseaseId": "advanced-agents",
    "parentDiseaseName": "Advanced & Resistant Pathogen Agents"
  },
  {
    "id": "colistin",
    "name": "Colistin (Polymyxin E)",
    "drugClass": "Polymyxin antibiotic",
    "parentDiseaseId": "advanced-agents",
    "parentDiseaseName": "Advanced & Resistant Pathogen Agents"
  },
  {
    "id": "tedizolid",
    "name": "Tedizolid",
    "drugClass": "Oxazolidinone antibiotic (2nd generation)",
    "parentDiseaseId": "advanced-agents",
    "parentDiseaseName": "Advanced & Resistant Pathogen Agents"
  },
  {
    "id": "posaconazole",
    "name": "Posaconazole",
    "drugClass": "Triazole antifungal",
    "parentDiseaseId": "advanced-agents",
    "parentDiseaseName": "Advanced & Resistant Pathogen Agents"
  },
  {
    "id": "liposomal-amphotericin-b",
    "name": "Liposomal Amphotericin B (L-AmB)",
    "drugClass": "Polyene antifungal — liposomal formulation",
    "parentDiseaseId": "advanced-agents",
    "parentDiseaseName": "Advanced & Resistant Pathogen Agents"
  }
];

export const DISEASE_SUMMARY_BY_ID: Record<string, DiseaseCatalogSummary> = Object.fromEntries(
  DISEASE_CATALOG.map((disease) => [disease.id, disease]),
);

export const MONOGRAPH_SUMMARY_BY_ID: Record<string, MonographCatalogSummary> = Object.fromEntries(
  MONOGRAPH_CATALOG.map((monograph) => [monograph.id, monograph]),
);
