import type { ContentMetaSeed } from "./editorial/content-meta";

// AUTO-GENERATED by scripts/generate-content-meta.js
// Run `npm run generate:content-meta` after changing editorial metadata.

export const DISEASE_CONTENT_META: Record<string, ContentMetaSeed> = {
  "uti": {
    "confidence": "high",
    "lastReviewed": "2026-03-09",
    "guidelineVersion": "IDSA 2025 cUTI guidance",
    "sources": [
      {
        "id": "idsa-2025-cuti",
        "citation": "Infectious Diseases Society of America complicated UTI guidance, 2025."
      },
      {
        "id": "idsa-escmid-2011-uti",
        "citation": "International Clinical Practice Guidelines for uncomplicated cystitis and pyelonephritis, 2011."
      },
      {
        "id": "eau-2024-uti",
        "citation": "European Association of Urology UTI guidance, 2024."
      }
    ],
    "reviewHistory": [
      {
        "reviewedOn": "2026-03-09",
        "reviewedBy": "PharmRef editorial review",
        "summary": "Reviewed 2025 cUTI reclassification, shorter-course recommendations, and IV-to-PO bacteremic UTI guidance."
      }
    ]
  },
  "cap": {
    "confidence": "high",
    "lastReviewed": "2026-03-09",
    "guidelineVersion": "ATS/IDSA 2019 CAP guidance",
    "sources": [
      {
        "id": "ats-idsa-2019-cap",
        "citation": "Adult community-acquired pneumonia guideline from ATS and IDSA, 2019."
      },
      {
        "id": "cape-cod",
        "citation": "Hydrocortisone for severe CAP, NEJM 2023."
      },
      {
        "id": "step-trial",
        "citation": "Three-day versus eight-day amoxicillin strategy for stabilized CAP, NEJM 2023."
      }
    ],
    "reviewHistory": [
      {
        "reviewedOn": "2026-03-09",
        "reviewedBy": "PharmRef editorial review",
        "summary": "Reviewed outpatient and inpatient CAP regimen selection, STEP short-course data, and severe CAP steroid updates."
      }
    ]
  },
  "hap-vap": {
    "confidence": "moderate",
    "lastReviewed": "2026-03-09",
    "guidelineVersion": "ATS/IDSA 2016 HAP/VAP guidance",
    "sources": [
      {
        "id": "ats-idsa-2016-hap-vap",
        "citation": "Hospital-acquired and ventilator-associated pneumonia guideline, 2016."
      },
      {
        "id": "idsa-2024-amr",
        "citation": "Antimicrobial resistance guidance used for resistant gram-negative escalation decisions, 2024."
      },
      {
        "id": "smart-trial",
        "citation": "Balanced crystalloids versus saline in ICU patients, NEJM 2018."
      }
    ],
    "reviewHistory": [
      {
        "reviewedOn": "2026-03-09",
        "reviewedBy": "PharmRef editorial review",
        "summary": "Reviewed HAP/VAP empiric coverage, resistant gram-negative escalation, and ICU stewardship framing."
      }
    ]
  },
  "ssti": {
    "confidence": "moderate",
    "lastReviewed": "2026-03-09",
    "guidelineVersion": "IDSA SSTI guidance",
    "sources": [
      {
        "id": "idsa-2014-ssti",
        "citation": "Skin and soft tissue infection guidance from IDSA."
      },
      {
        "id": "idsa-2024-amr",
        "citation": "Resistant organism escalation guidance, 2024."
      },
      {
        "id": "oviva",
        "citation": "Oral versus intravenous antibiotics for bone and joint and deep infection pathways, NEJM 2019."
      }
    ],
    "reviewHistory": [
      {
        "reviewedOn": "2026-03-09",
        "reviewedBy": "PharmRef editorial review",
        "summary": "Reviewed purulent and nonpurulent SSTI pathways, MRSA coverage boundaries, and oral step-down strategy."
      }
    ]
  },
  "iai": {
    "confidence": "moderate",
    "lastReviewed": "2026-03-09",
    "guidelineVersion": "SIS/IDSA intra-abdominal infection guidance",
    "sources": [
      {
        "id": "sis-idsa-iai",
        "citation": "Surgical Infection Society and IDSA intra-abdominal infection guidance."
      },
      {
        "id": "tokyo-guidelines",
        "citation": "Biliary and cholecystitis/cholangitis guidance used for source-control framing."
      },
      {
        "id": "stop-it",
        "citation": "Short-course antimicrobial therapy for source-controlled intra-abdominal infection, NEJM 2015."
      }
    ],
    "reviewHistory": [
      {
        "reviewedOn": "2026-03-09",
        "reviewedBy": "PharmRef editorial review",
        "summary": "Reviewed source-control-first IAI management, biliary coverage boundaries, and short-course post-control durations."
      }
    ]
  },
  "amr-gn": {
    "confidence": "high",
    "lastReviewed": "2026-03-09",
    "guidelineVersion": "IDSA 2024 AMR guidance",
    "sources": [
      {
        "id": "idsa-2024-amr",
        "citation": "Guidance for ESBL-E, CRE, DTR Pseudomonas, and resistant Acinetobacter, 2024."
      },
      {
        "id": "merino",
        "citation": "Piperacillin-tazobactam versus meropenem for ESBL bacteremia, JAMA 2018."
      },
      {
        "id": "pkpd-stewardship",
        "citation": "Extended-infusion beta-lactam stewardship principles used throughout resistant gram-negative pathways."
      }
    ],
    "reviewHistory": [
      {
        "reviewedOn": "2026-03-09",
        "reviewedBy": "PharmRef editorial review",
        "summary": "Reviewed IDSA AMR mechanism-based therapy, carbapenem-sparing strategy, and extended-infusion beta-lactam use."
      }
    ]
  },
  "bacteremia-endocarditis": {
    "confidence": "high",
    "lastReviewed": "2026-03-09",
    "guidelineVersion": "AHA/ACC 2023 IE update",
    "sources": [
      {
        "id": "aha-acc-2023-ie",
        "citation": "Infective endocarditis update from AHA/ACC, 2023."
      },
      {
        "id": "poet",
        "citation": "Partial oral treatment of endocarditis, NEJM 2019."
      },
      {
        "id": "arrest",
        "citation": "Adjunctive rifampin for Staphylococcus aureus bacteremia, Lancet 2018."
      }
    ],
    "reviewHistory": [
      {
        "reviewedOn": "2026-03-09",
        "reviewedBy": "PharmRef editorial review",
        "summary": "Reviewed bloodstream infection duration, endocarditis evaluation, and oral or OPAT transition criteria."
      }
    ]
  },
  "c-difficile": {
    "confidence": "high",
    "lastReviewed": "2026-03-09",
    "guidelineVersion": "IDSA/SHEA CDI guidance",
    "sources": [
      {
        "id": "idsa-shea-cdi",
        "citation": "Clostridioides difficile infection guideline from IDSA and SHEA."
      },
      {
        "id": "fidaxomicin-trials",
        "citation": "Registration and recurrence-reduction trials informing fidaxomicin preference."
      },
      {
        "id": "fmt-stewardship",
        "citation": "Evidence base for fecal microbiota transplant in multiply recurrent CDI."
      }
    ],
    "reviewHistory": [
      {
        "reviewedOn": "2026-03-09",
        "reviewedBy": "PharmRef editorial review",
        "summary": "Reviewed CDI severity stratification, fidaxomicin preference, and recurrence-prevention escalation."
      }
    ]
  },
  "bone-joint": {
    "confidence": "moderate",
    "lastReviewed": "2026-03-09",
    "guidelineVersion": "OVIVA-informed bone and joint guidance",
    "sources": [
      {
        "id": "oviva",
        "citation": "Oral versus intravenous antibiotics for bone and joint infection, NEJM 2019."
      },
      {
        "id": "idsa-pji-osteomyelitis",
        "citation": "IDSA guidance relevant to osteomyelitis and prosthetic joint infection pathways."
      },
      {
        "id": "orthopedic-id-review",
        "citation": "Orthopedic infection source-control and step-down stewardship literature."
      }
    ],
    "reviewHistory": [
      {
        "reviewedOn": "2026-03-09",
        "reviewedBy": "PharmRef editorial review",
        "summary": "Reviewed osteomyelitis and prosthetic-joint step-down strategy, source control, and OVIVA-aligned oral therapy."
      }
    ]
  },
  "cns-infections": {
    "confidence": "moderate",
    "lastReviewed": "2026-03-09",
    "guidelineVersion": "IDSA CNS infection guidance",
    "sources": [
      {
        "id": "idsa-meningitis-ventriculitis",
        "citation": "IDSA guidance for bacterial meningitis and healthcare-associated ventriculitis."
      },
      {
        "id": "aan-idsa-encephalitis",
        "citation": "Consensus references used for CNS diagnostic framing and adjunctive therapy."
      },
      {
        "id": "dexamethasone-meningitis",
        "citation": "Adjunctive dexamethasone trials informing pneumococcal meningitis care."
      }
    ],
    "reviewHistory": [
      {
        "reviewedOn": "2026-03-09",
        "reviewedBy": "PharmRef editorial review",
        "summary": "Reviewed meningitis and ventriculitis empiric therapy, adjunctive dexamethasone use, and CNS diagnostic priorities."
      }
    ]
  },
  "fungal-infections": {
    "confidence": "moderate",
    "lastReviewed": "2026-03-09",
    "guidelineVersion": "IDSA 2016 candidiasis and aspergillosis guidance",
    "sources": [
      {
        "id": "idsa-candidiasis",
        "citation": "Clinical practice guideline for candidiasis, IDSA 2016."
      },
      {
        "id": "idsa-aspergillosis",
        "citation": "Diagnosis and management of aspergillosis, IDSA 2016."
      },
      {
        "id": "secure-trial",
        "citation": "Isavuconazole versus voriconazole for invasive aspergillosis, Lancet 2016."
      }
    ],
    "reviewHistory": [
      {
        "reviewedOn": "2026-03-09",
        "reviewedBy": "PharmRef editorial review",
        "summary": "Reviewed candidiasis and aspergillosis first-line agents, salvage roles, and therapeutic monitoring priorities."
      }
    ]
  },
  "advanced-agents": {
    "confidence": "emerging",
    "lastReviewed": "2026-03-09",
    "guidelineVersion": "IDSA 2022-2024 resistant pathogen guidance",
    "sources": [
      {
        "id": "idsa-2024-amr",
        "citation": "Guidance for CRE, ESBL-E, DTR Pseudomonas, and resistant gram-negatives."
      },
      {
        "id": "aspect-program",
        "citation": "Ceftolozane-tazobactam registration studies for cUTI and nosocomial pneumonia."
      },
      {
        "id": "restore-imi",
        "citation": "Imipenem-cilastatin-relebactam versus polymyxin-based therapy."
      }
    ],
    "reviewHistory": [
      {
        "reviewedOn": "2026-03-09",
        "reviewedBy": "PharmRef editorial review",
        "summary": "Reviewed reserve-agent positioning for resistant gram-negatives and stewardship boundaries for novel therapies."
      }
    ]
  },
  "febrile-neutropenia": {
    "confidence": "moderate",
    "lastReviewed": "2026-03-09",
    "guidelineVersion": "IDSA febrile neutropenia guidance",
    "sources": [
      {
        "id": "idsa-febrile-neutropenia",
        "citation": "Guideline for evaluation and management of febrile neutropenia in cancer patients."
      },
      {
        "id": "nccn-fever-neutropenia",
        "citation": "NCCN references for risk stratification and outpatient eligibility."
      },
      {
        "id": "mascc-cisne",
        "citation": "Risk-stratification tools used for low-risk outpatient decision support."
      }
    ],
    "reviewHistory": [
      {
        "reviewedOn": "2026-03-09",
        "reviewedBy": "PharmRef editorial review",
        "summary": "Reviewed high-risk febrile neutropenia initial coverage, escalation triggers, and outpatient risk stratification."
      }
    ]
  },
  "diabetic-foot": {
    "confidence": "moderate",
    "lastReviewed": "2026-03-09",
    "guidelineVersion": "IWGDF/IDSA diabetic foot guidance",
    "sources": [
      {
        "id": "iwgdf-idsa-dfi",
        "citation": "Diabetic foot infection guidance from IWGDF and IDSA."
      },
      {
        "id": "osteomyelitis-stewardship",
        "citation": "Shorter-course and oral step-down literature for diabetic foot osteomyelitis."
      },
      {
        "id": "source-control-principles",
        "citation": "Surgical debridement and perfusion assessment references used in DFI pathways."
      }
    ],
    "reviewHistory": [
      {
        "reviewedOn": "2026-03-09",
        "reviewedBy": "PharmRef editorial review",
        "summary": "Reviewed diabetic foot severity staging, debridement and perfusion priorities, and osteomyelitis step-down options."
      }
    ]
  },
  "sepsis": {
    "confidence": "high",
    "lastReviewed": "2026-03-09",
    "guidelineVersion": "SSC 2021; IDSA 2024 sepsis antimicrobial guidance",
    "sources": [
      {
        "id": "ssc-2021",
        "citation": "Surviving Sepsis Campaign international guidelines, 2021."
      },
      {
        "id": "idsa-2024-sepsis",
        "citation": "Infectious disease-focused antimicrobial guidance for sepsis, 2024."
      },
      {
        "id": "balance",
        "citation": "Seven versus fourteen days for bloodstream infection, 2024."
      }
    ],
    "reviewHistory": [
      {
        "reviewedOn": "2026-03-09",
        "reviewedBy": "PharmRef editorial review",
        "summary": "Reviewed early sepsis antimicrobials, resistant-risk stratification, and shorter-course de-escalation evidence."
      }
    ]
  }
};

export const SUBCATEGORY_CONTENT_META: Record<string, ContentMetaSeed> = {
  "amr-gn/esbl-e": {
    "confidence": "high",
    "lastReviewed": "2026-03-09",
    "guidelineVersion": "IDSA 2024 ESBL-E guidance",
    "sources": [
      {
        "id": "idsa-2024-amr",
        "citation": "Guidance for ESBL-producing Enterobacterales, including preferred carbapenem use and oral step-down cautions, 2024."
      },
      {
        "id": "merino",
        "citation": "Piperacillin-tazobactam versus meropenem for ESBL bloodstream infection, JAMA 2018."
      },
      {
        "id": "pkpd-stewardship",
        "citation": "Extended-infusion beta-lactam principles applied to ESBL-E severe infection management."
      }
    ],
    "reviewHistory": [
      {
        "reviewedOn": "2026-03-09",
        "reviewedBy": "PharmRef editorial review",
        "summary": "Reviewed ESBL empiric boundaries, carbapenem preference, and oral step-down cautions."
      }
    ]
  },
  "amr-gn/cre-kpc": {
    "confidence": "high",
    "lastReviewed": "2026-03-09",
    "guidelineVersion": "IDSA 2024 KPC-CRE guidance",
    "sources": [
      {
        "id": "idsa-2024-amr",
        "citation": "Preferred beta-lactam/beta-lactamase inhibitor strategy for KPC-producing CRE, 2024."
      },
      {
        "id": "tango-ii",
        "citation": "Meropenem-vaborbactam versus best available therapy for CRE infections, 2018."
      },
      {
        "id": "reprise",
        "citation": "Ceftazidime-avibactam activity in resistant gram-negative infections, phase 3 data."
      }
    ],
    "reviewHistory": [
      {
        "reviewedOn": "2026-03-09",
        "reviewedBy": "PharmRef editorial review",
        "summary": "Reviewed KPC-CRE preferred BL/BLI therapy and definitive selection criteria."
      }
    ]
  },
  "amr-gn/cre-mbl": {
    "confidence": "moderate",
    "lastReviewed": "2026-03-09",
    "guidelineVersion": "IDSA 2024 MBL-CRE guidance",
    "sources": [
      {
        "id": "idsa-2024-amr",
        "citation": "Aztreonam plus avibactam-based strategy and cefiderocol considerations for MBL producers, 2024."
      },
      {
        "id": "aztreonam-avibactam-evidence",
        "citation": "Observational and mechanistic literature supporting aztreonam plus ceftazidime-avibactam for NDM/VIM/IMP producers."
      },
      {
        "id": "credible-cr",
        "citation": "Cefiderocol data in carbapenem-resistant gram-negative infections."
      }
    ],
    "reviewHistory": [
      {
        "reviewedOn": "2026-03-09",
        "reviewedBy": "PharmRef editorial review",
        "summary": "Reviewed MBL-CRE salvage strategy, aztreonam combination use, and cefiderocol role."
      }
    ]
  },
  "amr-gn/dtr-pa": {
    "confidence": "moderate",
    "lastReviewed": "2026-03-09",
    "guidelineVersion": "IDSA 2024 DTR Pseudomonas guidance",
    "sources": [
      {
        "id": "idsa-2024-amr",
        "citation": "Preferred newer beta-lactams and susceptibility-based escalation framework for DTR Pseudomonas, 2024."
      },
      {
        "id": "aspect-np",
        "citation": "Ceftolozane-tazobactam for nosocomial pneumonia including resistant Pseudomonas."
      },
      {
        "id": "restore-imi",
        "citation": "Imipenem-cilastatin-relebactam versus colistin-based therapy for imipenem-nonsusceptible infections."
      }
    ],
    "reviewHistory": [
      {
        "reviewedOn": "2026-03-09",
        "reviewedBy": "PharmRef editorial review",
        "summary": "Reviewed DTR Pseudomonas susceptibility-based escalation and newer beta-lactam positioning."
      }
    ]
  },
  "amr-gn/crab-steno": {
    "confidence": "emerging",
    "lastReviewed": "2026-03-09",
    "guidelineVersion": "IDSA 2024 CRAB/Stenotrophomonas guidance",
    "sources": [
      {
        "id": "idsa-2024-amr",
        "citation": "Guidance for CRAB and Stenotrophomonas with emphasis on combination therapy and selective use of newer agents, 2024."
      },
      {
        "id": "attack",
        "citation": "Sulbactam-durlobactam versus colistin for Acinetobacter baumannii-calcoaceticus complex infection, 2023."
      },
      {
        "id": "credible-cr",
        "citation": "Cefiderocol resistant gram-negative outcomes including Acinetobacter subgroup concerns."
      }
    ],
    "reviewHistory": [
      {
        "reviewedOn": "2026-03-09",
        "reviewedBy": "PharmRef editorial review",
        "summary": "Reviewed CRAB and Stenotrophomonas combination strategies and limited-agent stewardship."
      }
    ]
  },
  "advanced-agents/cre-management": {
    "confidence": "moderate",
    "lastReviewed": "2026-03-09",
    "guidelineVersion": "Advanced CRE agent review 2024",
    "sources": [
      {
        "id": "idsa-2024-amr",
        "citation": "Agent selection across KPC, OXA, and MBL resistance mechanisms."
      },
      {
        "id": "tango-ii",
        "citation": "Meropenem-vaborbactam comparative data in CRE infections."
      },
      {
        "id": "reprise",
        "citation": "Ceftazidime-avibactam resistant gram-negative treatment data."
      }
    ],
    "reviewHistory": [
      {
        "reviewedOn": "2026-03-09",
        "reviewedBy": "PharmRef editorial review",
        "summary": "Reviewed mechanism-specific CRE agent selection across KPC, OXA, and MBL phenotypes."
      }
    ]
  },
  "advanced-agents/mdr-pseudomonas": {
    "confidence": "moderate",
    "lastReviewed": "2026-03-09",
    "guidelineVersion": "Advanced DTR Pseudomonas agent review 2024",
    "sources": [
      {
        "id": "idsa-2024-amr",
        "citation": "Mechanism-aware DTR Pseudomonas escalation strategy."
      },
      {
        "id": "aspect-np",
        "citation": "Ceftolozane-tazobactam pulmonary efficacy data."
      },
      {
        "id": "restore-imi",
        "citation": "Imipenem-cilastatin-relebactam data for imipenem-resistant Pseudomonas."
      }
    ],
    "reviewHistory": [
      {
        "reviewedOn": "2026-03-09",
        "reviewedBy": "PharmRef editorial review",
        "summary": "Reviewed advanced agent positioning for MDR Pseudomonas and susceptibility-guided de-escalation."
      }
    ]
  },
  "febrile-neutropenia/high-risk-fn": {
    "confidence": "high",
    "lastReviewed": "2026-03-09",
    "guidelineVersion": "IDSA/NCCN high-risk FN guidance",
    "sources": [
      {
        "id": "idsa-febrile-neutropenia",
        "citation": "High-risk inpatient febrile neutropenia management and initial anti-pseudomonal coverage."
      },
      {
        "id": "nccn-fever-neutropenia",
        "citation": "Risk-based escalation and antifungal trigger guidance."
      },
      {
        "id": "mascc-cisne",
        "citation": "Risk tools used to separate outpatient from high-risk inpatient care."
      }
    ],
    "reviewHistory": [
      {
        "reviewedOn": "2026-03-09",
        "reviewedBy": "PharmRef editorial review",
        "summary": "Reviewed initial anti-pseudomonal coverage and inpatient escalation thresholds for high-risk febrile neutropenia."
      }
    ]
  },
  "febrile-neutropenia/fn-with-fungal-risk": {
    "confidence": "moderate",
    "lastReviewed": "2026-03-09",
    "guidelineVersion": "Persistent FN fungal-risk guidance",
    "sources": [
      {
        "id": "idsa-febrile-neutropenia",
        "citation": "Persistent fever evaluation and empiric antifungal thresholds."
      },
      {
        "id": "idsa-aspergillosis",
        "citation": "Diagnostic and treatment framing for invasive mold infection."
      },
      {
        "id": "galactomannan-ct-strategy",
        "citation": "High-resolution CT and serial biomarker literature in prolonged neutropenia."
      }
    ],
    "reviewHistory": [
      {
        "reviewedOn": "2026-03-09",
        "reviewedBy": "PharmRef editorial review",
        "summary": "Reviewed persistent-fever fungal evaluation triggers, imaging strategy, and empiric mold coverage."
      }
    ]
  },
  "bacteremia-endocarditis/sab-workup": {
    "confidence": "high",
    "lastReviewed": "2026-03-09",
    "guidelineVersion": "SAB workup and IE-screening review 2023",
    "sources": [
      {
        "id": "aha-acc-2023-ie",
        "citation": "Imaging, blood culture clearance, and infective endocarditis workup standards relevant to S. aureus bacteremia."
      },
      {
        "id": "arrest",
        "citation": "Adjunctive rifampin trial reinforcing the need for disciplined SAB management and source control, Lancet 2018."
      },
      {
        "id": "sab-bundle-literature",
        "citation": "Management-bundle and echocardiography literature for high-risk S. aureus bacteremia."
      }
    ],
    "reviewHistory": [
      {
        "reviewedOn": "2026-03-09",
        "reviewedBy": "PharmRef editorial review",
        "summary": "Reviewed S. aureus bacteremia bundle elements, repeat-culture timing, and echocardiography triggers."
      }
    ]
  },
  "bacteremia-endocarditis/native-valve-ie": {
    "confidence": "high",
    "lastReviewed": "2026-03-09",
    "guidelineVersion": "AHA/ACC 2023 native-valve IE update",
    "sources": [
      {
        "id": "aha-acc-2023-ie",
        "citation": "Current diagnostic and treatment recommendations for native-valve infective endocarditis."
      },
      {
        "id": "poet",
        "citation": "Partial oral treatment strategy in stabilized left-sided infective endocarditis, NEJM 2019."
      },
      {
        "id": "endocarditis-surgery-review",
        "citation": "Operative timing and multidisciplinary endocarditis-team literature."
      }
    ],
    "reviewHistory": [
      {
        "reviewedOn": "2026-03-09",
        "reviewedBy": "PharmRef editorial review",
        "summary": "Reviewed native-valve endocarditis diagnostic criteria, surgical triggers, and oral step-down boundaries."
      }
    ]
  },
  "bacteremia-endocarditis/prosthetic-valve-ie": {
    "confidence": "moderate",
    "lastReviewed": "2026-03-09",
    "guidelineVersion": "AHA/ACC 2023 prosthetic-valve IE update",
    "sources": [
      {
        "id": "aha-acc-2023-ie",
        "citation": "Guidance for prosthetic-valve endocarditis, surgery triggers, and organism-directed therapy."
      },
      {
        "id": "prosthetic-valve-ie-literature",
        "citation": "Observational evidence and surgical literature for prosthetic-valve endocarditis."
      },
      {
        "id": "rifampin-gentamicin-stewardship",
        "citation": "Evidence reassessment for adjunctive rifampin and aminoglycosides in prosthetic-valve IE."
      }
    ],
    "reviewHistory": [
      {
        "reviewedOn": "2026-03-09",
        "reviewedBy": "PharmRef editorial review",
        "summary": "Reviewed prosthetic-valve endocarditis adjunctive therapy risks and multidisciplinary surgical timing."
      }
    ]
  },
  "bacteremia-endocarditis/gram-negative-bacteremia": {
    "confidence": "high",
    "lastReviewed": "2026-03-09",
    "guidelineVersion": "Modern uncomplicated GNB duration review",
    "sources": [
      {
        "id": "balance",
        "citation": "Seven versus fourteen days for bloodstream infection, 2024."
      },
      {
        "id": "yahav-short-course-gnb",
        "citation": "Seven versus fourteen days for uncomplicated gram-negative bacteremia, 2019."
      },
      {
        "id": "oral-stepdown-bacteremia",
        "citation": "IV-to-oral transition and source-specific duration literature for uncomplicated gram-negative bacteremia."
      }
    ],
    "reviewHistory": [
      {
        "reviewedOn": "2026-03-09",
        "reviewedBy": "PharmRef editorial review",
        "summary": "Reviewed uncomplicated gram-negative bacteremia duration evidence and IV-to-PO transition criteria."
      }
    ]
  },
  "bacteremia-endocarditis/opat-considerations": {
    "confidence": "moderate",
    "lastReviewed": "2026-03-09",
    "guidelineVersion": "OPAT stewardship review 2024",
    "sources": [
      {
        "id": "aha-acc-2023-ie",
        "citation": "Outpatient treatment considerations and follow-up needs for stabilized endocarditis and bacteremia."
      },
      {
        "id": "poet",
        "citation": "Selective oral step-down model for stable endocarditis patients."
      },
      {
        "id": "opat-stewardship",
        "citation": "Monitoring, line-care, and adverse-event prevention literature for outpatient parenteral therapy."
      }
    ],
    "reviewHistory": [
      {
        "reviewedOn": "2026-03-09",
        "reviewedBy": "PharmRef editorial review",
        "summary": "Reviewed OPAT eligibility, monitoring burden, and complications that should block outpatient therapy."
      }
    ]
  },
  "sepsis/sepsis-community": {
    "confidence": "high",
    "lastReviewed": "2026-03-09",
    "guidelineVersion": "Community-acquired sepsis empiric review 2024",
    "sources": [
      {
        "id": "ssc-2021",
        "citation": "Early sepsis recognition, antibiotics, and hemodynamic management."
      },
      {
        "id": "idsa-2024-sepsis",
        "citation": "Antimicrobial source-based empiric framing and de-escalation priorities."
      },
      {
        "id": "clovers",
        "citation": "Fluid strategy data after initial sepsis resuscitation, NEJM 2023."
      }
    ],
    "reviewHistory": [
      {
        "reviewedOn": "2026-03-09",
        "reviewedBy": "PharmRef editorial review",
        "summary": "Reviewed community-onset sepsis empiric framing and early narrowing after source clarification."
      }
    ]
  },
  "sepsis/sepsis-hcap": {
    "confidence": "moderate",
    "lastReviewed": "2026-03-09",
    "guidelineVersion": "Healthcare-associated sepsis empiric review 2024",
    "sources": [
      {
        "id": "ssc-2021",
        "citation": "Core septic shock bundle and timing recommendations."
      },
      {
        "id": "idsa-2024-sepsis",
        "citation": "Healthcare exposure, resistant-pathogen risk, and de-escalation framing for sepsis."
      },
      {
        "id": "amr-risk-stratification",
        "citation": "Mechanism-aware resistant-pathogen coverage principles for healthcare-associated sepsis."
      }
    ],
    "reviewHistory": [
      {
        "reviewedOn": "2026-03-09",
        "reviewedBy": "PharmRef editorial review",
        "summary": "Reviewed healthcare-exposure resistance risk, broader empiric coverage boundaries, and de-escalation triggers."
      }
    ]
  },
  "sepsis/septic-shock": {
    "confidence": "high",
    "lastReviewed": "2026-03-09",
    "guidelineVersion": "SSC 2021 septic shock guidance",
    "sources": [
      {
        "id": "ssc-2021",
        "citation": "Septic shock bundles, vasopressor targets, and early antimicrobial recommendations."
      },
      {
        "id": "clovers",
        "citation": "Restrictive versus liberal fluids after initial resuscitation in sepsis, NEJM 2023."
      },
      {
        "id": "balance",
        "citation": "Shorter-course bloodstream infection data informing de-escalation once source control is achieved, 2024."
      }
    ],
    "reviewHistory": [
      {
        "reviewedOn": "2026-03-09",
        "reviewedBy": "PharmRef editorial review",
        "summary": "Reviewed septic shock antimicrobial timing, hemodynamic support references, and post-control de-escalation."
      }
    ]
  }
};

export const MONOGRAPH_CONTENT_META: Record<string, ContentMetaSeed> = {
  "ceftazidime-avibactam": {
    "confidence": "moderate",
    "lastReviewed": "2026-03-09",
    "guidelineVersion": "KPC-CRE and resistant Enterobacterales data",
    "sources": [
      {
        "id": "idsa-2024-amr",
        "citation": "Preferred use for KPC-producing CRE and other select resistant gram-negative infections."
      },
      {
        "id": "reprise",
        "citation": "Phase 3 ceftazidime-avibactam data in ceftazidime-resistant gram-negative infections."
      },
      {
        "id": "kpc-observational-outcomes",
        "citation": "Real-world outcomes literature in bloodstream and deep-seated KPC infections."
      }
    ],
    "reviewHistory": [
      {
        "reviewedOn": "2026-03-09",
        "reviewedBy": "PharmRef editorial review",
        "summary": "Reviewed KPC-CRE positioning, definitive-use boundaries, and outcome data for deep-seated infection."
      }
    ]
  },
  "meropenem-vaborbactam": {
    "confidence": "moderate",
    "lastReviewed": "2026-03-09",
    "guidelineVersion": "KPC-CRE beta-lactam/BLI data",
    "sources": [
      {
        "id": "idsa-2024-amr",
        "citation": "Preferred KPC-producing CRE therapy when susceptible."
      },
      {
        "id": "tango-ii",
        "citation": "Comparative meropenem-vaborbactam outcomes versus best available therapy for CRE infections."
      },
      {
        "id": "tango-i",
        "citation": "Registration data for complicated urinary tract infection."
      }
    ],
    "reviewHistory": [
      {
        "reviewedOn": "2026-03-09",
        "reviewedBy": "PharmRef editorial review",
        "summary": "Reviewed KPC-CRE efficacy data, definitive-use positioning, and cUTI registration support."
      }
    ]
  },
  "cefiderocol": {
    "confidence": "emerging",
    "lastReviewed": "2026-03-09",
    "guidelineVersion": "Cefiderocol resistant gram-negative evidence review",
    "sources": [
      {
        "id": "idsa-2024-amr",
        "citation": "Selective use in MBL producers and salvage scenarios."
      },
      {
        "id": "credible-cr",
        "citation": "Pathogen-specific outcomes and mortality signal discussion in CR infections."
      },
      {
        "id": "apeks-np",
        "citation": "Nosocomial pneumonia noninferiority data including resistant gram-negative organisms."
      }
    ],
    "reviewHistory": [
      {
        "reviewedOn": "2026-03-09",
        "reviewedBy": "PharmRef editorial review",
        "summary": "Reviewed salvage use in MBL and resistant gram-negative infections and outcome-signal cautions."
      }
    ]
  },
  "ceftolozane-tazobactam": {
    "confidence": "moderate",
    "lastReviewed": "2026-03-09",
    "guidelineVersion": "DTR Pseudomonas targeted beta-lactam data",
    "sources": [
      {
        "id": "idsa-2024-amr",
        "citation": "Preferred use for difficult-to-treat Pseudomonas when susceptible."
      },
      {
        "id": "aspect-np",
        "citation": "Phase 3 HAP/VAP data with resistant Pseudomonas representation."
      },
      {
        "id": "aspect-cuti-ciai",
        "citation": "Registration studies informing dosing and exposure targets."
      }
    ],
    "reviewHistory": [
      {
        "reviewedOn": "2026-03-09",
        "reviewedBy": "PharmRef editorial review",
        "summary": "Reviewed DTR Pseudomonas positioning, pulmonary data, and exposure-driven dosing considerations."
      }
    ]
  },
  "imipenem-cilastatin-relebactam": {
    "confidence": "moderate",
    "lastReviewed": "2026-03-09",
    "guidelineVersion": "Relebactam resistant Pseudomonas and CRE data",
    "sources": [
      {
        "id": "idsa-2024-amr",
        "citation": "Mechanism-based use in select KPC and DTR Pseudomonas isolates."
      },
      {
        "id": "restore-imi",
        "citation": "Comparative outcomes versus colistin-based therapy in imipenem-nonsusceptible infections."
      },
      {
        "id": "restore-imi-2",
        "citation": "Nosocomial pneumonia data for imipenem-cilastatin-relebactam."
      }
    ],
    "reviewHistory": [
      {
        "reviewedOn": "2026-03-09",
        "reviewedBy": "PharmRef editorial review",
        "summary": "Reviewed relebactam use in resistant Pseudomonas and KPC-CRE with comparative outcome data."
      }
    ]
  },
  "colistin": {
    "confidence": "emerging",
    "lastReviewed": "2026-03-09",
    "guidelineVersion": "Colistin salvage-use evidence review",
    "sources": [
      {
        "id": "idsa-2024-amr",
        "citation": "Reserve role due to nephrotoxicity and inferior outcomes when newer agents are available."
      },
      {
        "id": "aida",
        "citation": "Colistin-based combination therapy data in carbapenem-resistant gram-negative infection."
      },
      {
        "id": "polymyxin-toxicity",
        "citation": "Nephrotoxicity and PK limitations of polymyxins in critically ill patients."
      }
    ],
    "reviewHistory": [
      {
        "reviewedOn": "2026-03-09",
        "reviewedBy": "PharmRef editorial review",
        "summary": "Reviewed nephrotoxicity-limited salvage role and reasons to prefer newer agents when available."
      }
    ]
  },
  "tedizolid": {
    "confidence": "emerging",
    "lastReviewed": "2026-03-09",
    "guidelineVersion": "Tedizolid stewardship evidence review",
    "sources": [
      {
        "id": "absssi-labeling-stewardship",
        "citation": "Evidence base is strongest in skin/soft tissue infection rather than invasive MRSA infection."
      },
      {
        "id": "establish",
        "citation": "Tedizolid versus linezolid for acute bacterial skin and skin-structure infection."
      },
      {
        "id": "long-course-tedizolid",
        "citation": "Limited observational data for prolonged use outside labeled indications."
      }
    ],
    "reviewHistory": [
      {
        "reviewedOn": "2026-03-09",
        "reviewedBy": "PharmRef editorial review",
        "summary": "Reviewed off-label stewardship limits, skin-structure data, and prolonged-use uncertainty."
      }
    ]
  },
  "posaconazole": {
    "confidence": "moderate",
    "lastReviewed": "2026-03-09",
    "guidelineVersion": "Posaconazole prophylaxis and salvage-use data",
    "sources": [
      {
        "id": "idsa-aspergillosis",
        "citation": "Role in prophylaxis and salvage therapy for invasive mold disease."
      },
      {
        "id": "aml-mds-prophylaxis",
        "citation": "Posaconazole prophylaxis superiority in prolonged neutropenia."
      },
      {
        "id": "therapeutic-drug-monitoring",
        "citation": "Exposure targets and formulation-specific PK guidance."
      }
    ],
    "reviewHistory": [
      {
        "reviewedOn": "2026-03-09",
        "reviewedBy": "PharmRef editorial review",
        "summary": "Reviewed prophylaxis indications, salvage therapy role, and therapeutic drug monitoring targets."
      }
    ]
  },
  "liposomal-amphotericin-b": {
    "confidence": "moderate",
    "lastReviewed": "2026-03-09",
    "guidelineVersion": "L-AmB invasive fungal infection guidance",
    "sources": [
      {
        "id": "idsa-candidiasis-aspergillosis",
        "citation": "Core role in invasive candidiasis salvage and mold-active therapy."
      },
      {
        "id": "mucormycosis-guidance",
        "citation": "First-line role in mucormycosis and severe endemic mycoses."
      },
      {
        "id": "nephrotoxicity-mitigation",
        "citation": "Dose, electrolyte, and renal monitoring literature for lipid amphotericin formulations."
      }
    ],
    "reviewHistory": [
      {
        "reviewedOn": "2026-03-09",
        "reviewedBy": "PharmRef editorial review",
        "summary": "Reviewed invasive mold and mucormycosis role with renal and electrolyte monitoring priorities."
      }
    ]
  },
  "vancomycin": {
    "confidence": "high",
    "lastReviewed": "2026-03-09",
    "guidelineVersion": "AUC-guided vancomycin monitoring review",
    "sources": [
      {
        "id": "ashp-idsa-pids-2020-vancomycin",
        "citation": "Consensus guideline for AUC-guided therapeutic monitoring of vancomycin."
      },
      {
        "id": "aha-acc-2023-ie",
        "citation": "Organism-specific roles for vancomycin in endocarditis and bloodstream infection."
      },
      {
        "id": "auc-stewardship",
        "citation": "Clinical outcomes and nephrotoxicity literature supporting AUC-guided dosing."
      }
    ],
    "reviewHistory": [
      {
        "reviewedOn": "2026-03-09",
        "reviewedBy": "PharmRef editorial review",
        "summary": "Reviewed AUC-guided dosing, bacteremia and endocarditis roles, and nephrotoxicity mitigation."
      }
    ]
  },
  "daptomycin": {
    "confidence": "moderate",
    "lastReviewed": "2026-03-09",
    "guidelineVersion": "High-dose daptomycin SAB/IE review",
    "sources": [
      {
        "id": "aha-acc-2023-ie",
        "citation": "Daptomycin role in right-sided and left-sided staphylococcal endocarditis management."
      },
      {
        "id": "high-dose-daptomycin",
        "citation": "Bacteremia and endocarditis outcomes with high-dose daptomycin strategies."
      },
      {
        "id": "combination-salvage-therapy",
        "citation": "Evidence for daptomycin-based salvage approaches in persistent MRSA bacteremia."
      }
    ],
    "reviewHistory": [
      {
        "reviewedOn": "2026-03-09",
        "reviewedBy": "PharmRef editorial review",
        "summary": "Reviewed high-dose SAB and endocarditis use, salvage combinations, and monitoring priorities."
      }
    ]
  },
  "cefazolin": {
    "confidence": "moderate",
    "lastReviewed": "2026-03-09",
    "guidelineVersion": "MSSA bacteremia beta-lactam review",
    "sources": [
      {
        "id": "aha-acc-2023-ie",
        "citation": "Cefazolin role in MSSA bacteremia and endocarditis treatment."
      },
      {
        "id": "cefazolin-versus-asp",
        "citation": "Comparative outcomes literature against anti-staphylococcal penicillins in MSSA bacteremia."
      },
      {
        "id": "cefazolin-inoculum-effect",
        "citation": "Pharmacodynamic and inoculum-effect literature relevant to deep-seated MSSA infection."
      }
    ],
    "reviewHistory": [
      {
        "reviewedOn": "2026-03-09",
        "reviewedBy": "PharmRef editorial review",
        "summary": "Reviewed MSSA bacteremia role, inoculum-effect caveats, and beta-lactam comparative outcomes."
      }
    ]
  },
  "nafcillin": {
    "confidence": "moderate",
    "lastReviewed": "2026-03-09",
    "guidelineVersion": "Anti-staphylococcal penicillin review",
    "sources": [
      {
        "id": "aha-acc-2023-ie",
        "citation": "Preferred beta-lactam therapy framework for MSSA endocarditis."
      },
      {
        "id": "mssa-bacteremia-literature",
        "citation": "Historical standard-of-care outcomes with nafcillin and oxacillin."
      },
      {
        "id": "opat-tolerability",
        "citation": "Hepatic, renal, and sodium-load considerations during prolonged anti-staphylococcal penicillin therapy."
      }
    ],
    "reviewHistory": [
      {
        "reviewedOn": "2026-03-09",
        "reviewedBy": "PharmRef editorial review",
        "summary": "Reviewed anti-staphylococcal penicillin use in deep MSSA infection and OPAT tolerability tradeoffs."
      }
    ]
  },
  "ceftriaxone": {
    "confidence": "moderate",
    "lastReviewed": "2026-03-09",
    "guidelineVersion": "Ceftriaxone endocarditis/OPAT review",
    "sources": [
      {
        "id": "aha-acc-2023-ie",
        "citation": "Ceftriaxone role in streptococcal endocarditis and select gram-negative bloodstream infections."
      },
      {
        "id": "once-daily-opat",
        "citation": "Ceftriaxone suitability for outpatient therapy and simplified administration."
      },
      {
        "id": "biliary-urinary-source-bacteremia",
        "citation": "Source-specific stewardship literature supporting ceftriaxone de-escalation when susceptible."
      }
    ],
    "reviewHistory": [
      {
        "reviewedOn": "2026-03-09",
        "reviewedBy": "PharmRef editorial review",
        "summary": "Reviewed streptococcal endocarditis and bloodstream infection role with once-daily OPAT advantages."
      }
    ]
  }
};

export const PRIORITY_SUBCATEGORY_META_KEYS = [
  "amr-gn/esbl-e",
  "amr-gn/cre-kpc",
  "amr-gn/cre-mbl",
  "amr-gn/dtr-pa",
  "amr-gn/crab-steno",
  "advanced-agents/cre-management",
  "advanced-agents/mdr-pseudomonas",
  "febrile-neutropenia/high-risk-fn",
  "febrile-neutropenia/fn-with-fungal-risk",
  "bacteremia-endocarditis/sab-workup",
  "bacteremia-endocarditis/native-valve-ie",
  "bacteremia-endocarditis/prosthetic-valve-ie",
  "bacteremia-endocarditis/gram-negative-bacteremia",
  "bacteremia-endocarditis/opat-considerations",
  "sepsis/sepsis-community",
  "sepsis/sepsis-hcap",
  "sepsis/septic-shock"
] as const;

export const PRIORITY_MONOGRAPH_META_KEYS = [
  "ceftazidime-avibactam",
  "meropenem-vaborbactam",
  "cefiderocol",
  "ceftolozane-tazobactam",
  "imipenem-cilastatin-relebactam",
  "colistin",
  "tedizolid",
  "posaconazole",
  "liposomal-amphotericin-b",
  "vancomycin",
  "daptomycin",
  "cefazolin",
  "nafcillin",
  "ceftriaxone"
] as const;
